zulip/zulip-terminal

core.py, helper.py, model.py, ui.py, ui_tools.py
UsersView, StreamsView and MessageBox View support scrolling.
Message click opens write box with relevant field(s) prefilled.
Update Screen on getting new updates using `loop.draw_screen()` method.
=> Zulip-Terminal: Support Scrolling and use Stream ID to store stream messages.

README.md, core.py, helper.py, model.py
Use json instead of ujson to load/dump objects.
Explicitly use `pip3` instead of `pip` in installation instructions.
Support self messages in PM.
=> Zulip-Terminal: Minor Bug Fixes.

README.md, ui_tools.py
`c` hotkey will be useful when the user wants to compose a message in the same stream but in a different topic.
=> hotkeys: Add `c` to compose a new stream message.

README.md, zulipterminal/ui_tools/boxes.py
Use `Alt enter to send messages.`
`Ctrl enter` is not used due to some issues in using it with
different terminals.
=> ui: Add feature to send multiline messages.

zulipterminal/model.py
Including `realm_user` in `fetch_event_types` loads a lot of
useless data and increases startup time.
=> model: Use `client.get_members` method to get user data.

zulipterminal/ui_tools/views.py
Old/new messages were not loading when user was at the end of
new/old messages due to custom mapping of key board shortcuts 'j'
and 'k'.
=> hotkeys: Fix not loading of old/new messages.

README.md
=> Explicitly use Python 3 when installing zulip-terminal using pipsi

zulipterminal/core.py, zulipterminal/ui.py
Look at https://github.com/urwid/urwid/issues/264#issuecomment-358633735 for more details.
=> run: Support running in WSL by replacing SI/SO.

zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
urwid_readline automatically inserts a new line so we don't need
to do it manually.
We should send the real size of the keypress and not the
default size.
=> editor: Fix bugs related to `urwid_readline` library.

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui_tools/utils.py, zulipterminal/ui_tools/views.py
This introduces:
* `model.set_narrow`
* `model.get_focus_in_current_narrow`
* `model.set_focus_in_current_narrow`
It also migrates the `get_current_ids` method from `views.py` to `model.py`, since this is very model-specific code.
There are a few remaining accesses of `model.narrow`, but these are minor; I'd suggest a followup commit to rename `narrow` -> `_narrow` to clarify that this is intended as essentially a private variable.
Tests are also added and migrated, where applicable; other than seeking confirmation that this change seems reasonable, my concern is perhaps that I'm not using the existing test fixtures to the fullest extent, but perhaps this can be discussed further subsequently.
I've looked into further improving the encapsulation, of the index, but this is more challenging …
=> model: Improve encapsulation of narrow

tests/ui/test_ui.py, zulipterminal/ui.py, zulipterminal/ui_tools/buttons.py
These commits make incremental changes to ensure that when the window is "small", that various small features are visible; these are not optimal, but appear to be an improvement over the current state.
These include:
* Removing text insets in the streams and user windows, and the MenuButtons
* Simplifying the post-user text to avoid extra spaces
* Fixing the left and right columns to a semi-arbitrary fixed-25 width (which shows most chat.zulip.org streams, and most names, without wrapping)
* Using a `Frame` rather than a `LineBox` for the 'main window' (saves a few characters)
I also included an update to the last commit to show the 'connection', ie. name/email/server, rather than 'Zulip'. I'm not sure if some of this belongs in the View, or if the text should be prefaced with …
=> Small window improvements

zulipterminal/ui_tools/buttons.py
Advance emoijs don't work on many platforms for urwid. So replace
them simply with a BULLET.
=> ui: Change emojis before `All messages` and `PM Button`.

tests/core/test_core.py, zulipterminal/ui_tools/boxes.py
This does for private messages, what already exists for streams/topics, ie. combining conversation 'titles', as well as removing the user's name from the conversation to make it clearer.
=> Add private recipient grouping

zulipterminal/ui_tools/boxes.py
This broadly improves the layout of the central window, at least to my eye, by:
* shifting the date in line with the author-name (sender)
* omitting repeated author-names, where people send messages without another author replying
This also saves vertical space, through the first change, which was one original motivation.
The first commit is less necessary now, since the time is in the `main_view` method, but I still think is a reasonable functionality to extract.
Please give this a try to see the change in layout.
=> Improve messages output (MessageBox)

zulipterminal/ui_tools/boxes.py
This avoids giving a time to subsequent messages, if they have the same time (to the minute, as currently displayed). If the line normally containing the author and time is then empty, it is removed, saving a little more space.
This does lead to some messages (red-highlighted) with no explicitly associated time, but it seems ok?
=> boxes: Elide time if same as previous & author/time line if empty.

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
Running MainLoop.draw_screen in a  threaded process distorts the
screen. Setting up pipe method to always run draw_screen in
main thread removes all distortions.
=> ui: Remove distortions in ui by running draw_screen in main thread.

tests/model/test_model.py, zulipterminal/config.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This first stab at 'thumbs_up' works, but as with other cases of new messages being added to the message-view, doesn't quite update the view properly each time in ZT.
=> Add initial support for reactions via '+' key for thumbs_up.

zulipterminal/ui_tools/boxes.py
These figures are a little too embedded for my liking, but for now they make the wider-screen behavior much less cramped, while retaining more spacing than before.
=> boxes: Remove excess spacing in message display for wide screens.

zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
This spaces out the topic slightly from the stream and the dividing '>' character, adds a space after the topic, and then styles the 'bar'.
This is intended to bring back some of the topic separation/heading styling, but maintaining the stream/topic styling distinction.
=> boxes: Show topic changes by bar background & surrounding spaces.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This helps user to read content more easily.
=> message_view: Keep the focus widget in center of the view.

tests/model/test_model.py, zulipterminal/model.py, zulipterminal/ui.py
Set new_user_input to `False` after every request.
Set new_user_input to `True` on any keypress catched by urwid.
=> presence: Update user presence every minute.

tests/conftest.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/buttons.py
This PR shows private streams with a 'P' (rather than '#'), much like a lock is shown in the zulip web-app.
Current tests pass with the first commit; the second commit extends them to include a private-stream test-case and so improves the test coverage.
=> Mark private streams

zulipterminal/config.py, zulipterminal/helper.py, zulipterminal/ui_tools/boxes.py
* Reordered the shortcut key listing in the help (via `config.py`) to group similar commands;
* Collected together some typos I remembered from browsing the code.
The first one is small but important - if I scan the help and find 'new [something] message' I would expect to find 'new [otherthing] message' nearby, as well as how to reply, or edit messages, and the same for other aspects.
=> Reorder shortcut keys (& fix a few typos)

zulipterminal/ui_tools/boxes.py
This caused a crash; this commit checks for `element.attrs` in the
conditionals before getting the class.
See https://chat.zulip.org/#narrow/stream/9-issues/subject/Un-classed.20DIV.20in.20rendered.20content.3F/near/655208
=> bugfix: Elide divs/spans with no class in soup2markup.

README.md
The docs previously stated that the debug.log was generated in /tmp/debug.log however the default place for the output was ./debug.log with no file being generated in /tmp/debug.log. Correcting that.
=> Fix path to debug.log

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
These increase overall coverage by 0.5% and are a precursor to other commits which refactor the MessageBox code. One small code fix is also included, uncovered by adding the tests.
=> Add extra MessageBox tests

tests/conftest.py, tests/core/test_core.py, tests/helper/test_helper.py, zulipterminal/core.py, zulipterminal/helper.py
I fixed this while refactoring, but backported it since this seems to cause a crash on master.
I've added/amended tests/fixtures to include a multiple-recipient case, and if the commits are reordered (or the bugfix is removed) then the additional test indeed fails.
The bugfix commit itself is small and appears to work fine, and the `core.py` code is now more consistent with similar functions, however:
* it doesn't set `button.user_id` (it doesn't seem an issue?)
* was the different layout/branching of the old code important?
=> Bugfix: Update & access index correctly for multiple PM recipients

tests/ui/test_ui_tools.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
* Shows stars applied to messages in other clients
* Amends and adds tests related to the star-viewing code
* Refactor code to aid readability using additional dicts, `any` and comprehensions
Old tests amended, more tests added (coverage still at 65.7%).
=> Show starred messages & refactor MessageBox.main_view()

tests/test_config.py, zulipterminal/config.py
Originally motivated by broadening the `keypress` tests, which are currently hardcoded to specific keys rather than the `KEY_BINDINGS` in `config.py`, to iterate through listed possible keys. Then noticed this file was untested, thought of refactoring, but wanted to add (the minimal!) tests first :)
It turned out easier to write the `is_command_key` tests in terms of `keys_for_command`, hence the test infrastructure commit is currently separate reflecting my reordering.
PLEASE CHECK: The docstring for `is_command_key` currently indicates it returns "a key if mapped or the key otherwise". I've not intended to change this behavior, but it seems not to describe current master? I can incorporate this if relevant.
=> Add tests & extra function for config.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This may be due to a test issue with CI on one of my recent PRs which got merged anyhow?
Resolved by adjusting that code to cope with:
* python <3.5 does not support multiple dict unpacking
* python <3.6 does not have ~ordered dicts
=> Fix master for python 3.4/3.5

zulipterminal/ui_tools/boxes.py
The marker:
* is always present
* is colored according to read/unread/active status
* emphasizes how messages are separate when content_headers are shared
* indicates message status, when text cannot be colored
(eg. just bold/italic text, or just a user-mention).
I was going to implement this as a column of text, but getting the height correct seemed complex - particularly when a LineBox can be used, as suggested in #98. I experimented with fuller LineBox's, but decided upon the left-side since it's like the webapp, takes up less space, and looks good :)
This could be considered to resolve #98, but I'm not sure if the intent there was to make a distinction on shape alone, in case of a no-colored approach. Otherwise, this fixes #98, and perhaps a separate issue should track potential …
=> UI: Add marker to left of message.

zulipterminal/ui_tools/boxes.py
This makes the code clearer, and follows the style in the zulip webapp, as discussed here:
https://chat.zulip.org/#narrow/stream/101-design/subject/date.20separators/near/664541
=> Minor: Use 'recipient header' rather than 'header', as in webapp

.travis.yml, setup.py
Follow-up from chat in the last 24h confirming we should aim to support 3.4/3.5, as in existing travis CI setup.
Given that 3.7 is now out, I thought we could also add that, and so have updated the travis config for that and the `setup.py` file to indicate support for 3.4-3.7.
Current tests run fine for each version, as they stand.
=> deps: Support python 3.4-3.7 in travis & setup.py.

Pipfile, setup.py
I introduced the use of `TypedDict` to resolve a mypy issue, in an earlier commit; since this was in a dev environment, `mypy_extensions` was already installed and everything just worked, but this is not the case in a simple install, as mentioned at https://github.com/zulip/zulip-terminal/issues/163#issuecomment-439580517.
Ideally `TypedDict` will become a full and useful type in a later python, but for now the simplest approach appears to be to depend upon `mypy_extensions`.
=> deps: Require mypy_extensions>=0.4 for TypedDict.

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
Currently, when scrolling up or down beyond the messages currently "known", or when extra messages are sent from the server, they are simply added as an individual message in a new `MessageBox` with no context.
To include the context, this PR passes `last_message` to `create_msg_box_list` when adding to the bottom of the `MessageView`, and includes the top message in the messages to render when adding to the top (scrolling up).
Tests have been amended/added and give coverage, though could probably be improved upon further in future.
=> bugfix: Avoid showing extra recipient headers on scrolling/appending

zulipterminal/cli/run.py
If the `zuliprc` file is missing and the user is prompted for their credentials, pressing `Ctrl+C` (especially after a couple of failed attempts to authorise) will result in a traceback of uncaught exceptions. This is fixed by moving the call to `parse_zuliprc` into a try block.
=> Bugfix: Prevent leaking exceptions when Ctrl+C is pressed during authorisation

zulipterminal/helper.py, zulipterminal/ui_tools/buttons.py
This at least shows that muted streams are muted, whereas previously this was not obvious.
In the webapp the counts are currently still shown, but faded out; whether we duplicate that is not clear, but this at least shows that the streams are muted.
=> Add 'M' to indicate muted streams in place of absent count

zulipterminal/core.py, zulipterminal/ui_tools/views.py
This PR:
* switches the loop in `HelpView` into a list comprehension, and adds another to reduce duplication;
* saves visual space by removing blank lines and moving the (adjusted) title into the `LineBox` frame, reducing the need to scroll.
I've retained a blank line at the top, as it seems to separate the title/frame from the help better.
I think it would be good to connect the details on navigating the help with the help entries, but I think that is more a point for discussion.
=> Polish Help menu

setup.py
For a sufficiently up to date pip, we can specify python when installing using pip; given we test against 3.4-3.7 now, I set this to `>=3.4, <3.8`.
=> setup: Specify python requirements for pip>=9.

zulipterminal/config.py
This is in order to be consistent with the webapp.
A screenshot of the webapp key map exists at
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Narrowing.20behavior
=> config: Switch the key for stream narrow and topic narrow.

setup.py, tests/core/test_core.py, zulipterminal/core.py, zulipterminal/version.py
While exploring the code to check the agent being reported, I noticed the version was hard-coded and doesn't match `setup.py` (or pypi).
This PR pulls this from a central file for both, and given 0.2.1 is on pypi, I set the version to `0.2.1+git`.
=> Add version.py & use in core & setup.py.

tests/core/test_core.py, zulipterminal/config.py, zulipterminal/core.py
It seems reasonable to disable both of these since:
- we don't currently respond appropriately to ^Z
- flow control is probably not relevant at this point (we could disable ^Q as well as ^S?)
We could potentially enable/disable the latter two for use as shortcut keys, and amend the signal code in `core.py` at run-time, but for now it seems reasonable to just disable it.
Not excluding ^Q should be safe, since that resumes the flow after a ^S.
The second commit fixes #166, so [un]starring keys will then incorporate the webapp (but retain `*`).
=> Disable ctrl-z and ctrl-s (enabling star key use)

Pipfile, requirements.txt, setup.py
This has been fixed in master though I couldn't find the reason why. It would be safer to not install `typing` on newer version.
=> deps: Install typing only on < 3.5.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This fixes a bug found by @rht where scrolling up beyond the top of a topic caused a traceback:
```
Traceback (most recent call last):                                                                                                                │
File "/run/current-system/sw/lib/python3.7/threading.py", line 917, in _bootstrap_inner                                                         │
self.run()           │                                                                                                                        │
File "/run/current-system/sw/lib/python3.7/threading.py", line 865, in run                                                                      │
self._target(*self._args, **self._kwargs) …
```
=> Bugfix: Only update view if scrolling up & more messages exist

README.md, tests/conftest.py, tests/core/test_core.py, tests/helper/test_helper.py, tests/model/test_model.py, zulipterminal/config.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This completes my push to add starred message support; this was working some time ago, but is now sufficiently polished and tested to be a PR :)
I find this useful not just for marking messages as starred/unstarred (via `*` or `ctrl s` to toggle), but now also for showing those messages with just a key, and occasionally via the starred-message button.
Given the duplication in StarredButton, the last commit also is quite a simplification of similar buttons.
Also @amanagr `MenuButton` isn't used, correct? Could we remove that in a different PR?
=> Add Starred messages key (f) and button

CHANGELOG.md
I thought it would be useful to collate the changes since the last release; this is based on the git log since 0.2.0 was tagged; I'm not sure precisely what went into 0.2.1, and what to place under those versions.
=> CHANGELOG.md: Add file listing new git features & earlier versions.

zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/ui.py, zulipterminal/ui_tools/buttons.py
This PR validates theme selection before reaching the `Controller`, and includes much more error handling.
This was also motivated by theme specification on the command-line not being recognized - this PR shows where themes are being specified, both in the case of failure and success :)
I'm aware the code is all in the try block - this can be refactored out for cleanliness, but this feature seemed useful to have ASAP!
=> run/core: Validate & indicate source of themes early in run, not core.

zulipterminal/config/themes.py
Proof-of-concept of using 256-color mode with gruvbox theme (https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim).
Before:
After:
Still hardcoded. I should make 2 preparatory commits to: enable/disable the 256-color on terminals that support 256-color, conf to easily modify the color instead of at ui.py.
=> ui: Add 16:default,256:gruvbox colorscheme.

tests/model/test_model.py, zulipterminal/model.py
ZT is crashing if the user has all the messages read since the
anchor is then set to 10000000000000000 by zulip api.
This tries to set pointer to 10000000000000000 and since there aren't that many messages in zt, it crashes.
=> model: In case of all read msgs don't set pointer to received anchor.

tests/core/test_core.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/ui.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
The new autohide (the first commit) involves the following changes:
- Users list returns to the right side
- Initial view defaults to showing streams & messages, focused on home
- GO_LEFT/GO_RIGHT keys move into Streams/Users lists respectively
- Streams and Users lists autohide when moving away from them
- Two View methods are used to show/hide Streams & Users (left/right panels)
- View parameter added to MiddleColumnView __init__ for show/hide calls
The second commit then adds similar option behavior as recently added for themes, but to enable or disable the autohide behavior.
Try this out and let me know what you think :) It feels a lot more natural to me, but then again I wrote it!
=> Improved autohide behavior & zuliprc configuration option

tests/conftest.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This started as a follow-up to #211 - hence the `initial_index` commit, which avoids a need for `Optional[Index]` and lots of asserts - as well as being based on some older index-encapsulation work I had in another branch.
Subsequent commits are to:
- simplify `get_messages` (and avoid an error case) by returning `None`
- remove an unnecessary internal `index` being tracked in a view
- require the index parameter in `index_parameters` to be an `Index` (since it's initialized already)
- simplify (hopefully!) `set_narrow` via use of `locals()`, and a `dict` for the names/narrows
- simplify core (`Controller`) narrowing methods by using the `model.get_message_ids_in_current_narrow` method
- remove an unnecessary reset of the search index in `boxes.py`.
This works towards simplifying index …
=> Refactoring: indexing

.travis.yml
~This may or may not cache the pipenv files.~ Found the pipenv cache location, as per https://pipenv.readthedocs.io/en/latest/diagnose/. Added via 3rd commit.
=> Travis: Add darwin on build matrix.

CHANGELOG.md, README.md
This seems correct, but please check if this makes sense for those who have contributed :)
We should only merge this just before releasing, as it updates CHANGELOG to switch 'since last update' to '0.3.0'.
=> Link to CHANGELOG from README & add further entries for 0.3.0 release

tests/model/test_model.py, zulipterminal/model.py
"realm_user" was added to the initial register call to server but
client.get_members call wasn't removed which basically fetches the
data already included in "realm_user".
=> model: Remove unnecessary fetching of realm_users data twice.

tests/model/test_model.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/model.py
This should fix #216 via the last commit, as well as output errors if the `get_messages` or `user_id` calls fail. You can test the former just by running with no connection, and for the latter by adding a `time.sleep` call before the `_update_initial_data` call in `Model.__init__` and then eg. quickly turning off your wifi.
I spent a while investigating 'simpler' alternatives to the `ThreadPoolExecutor`, keeping `Thread`s around, but this seems pretty straightforward; the main motivation is that the `Future`s are a simple way to return an error status, rather than setting eg. values in passed-in list variables, or using a `Queue`. It was more obviously useful when there was another thread for `_update_realm_users`, but that's clearly not relevant now (as I suspected at some point …
=> Improved model (client-server) error handling

tests/core/test_core.py, tests/model/test_model.py, zulipterminal/core.py, zulipterminal/model.py
Currently there is a `fetch_event_types` register call in `Model`, and an `event_types` register call in `Controller` (in core). This PR brings the latter into the `Model`, and then combines them to use a single `register` call to the API. The method moved across is maintained for re-use in the case of the server queue being garbage-collected, with the `event_types` data extracted into the top of the `Model` itself.
This was discussed in this topic:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/subject/Fetching.20realm_users/near/677096
=> Centralize client.register calls into Model & combine

tests/model/test_model.py, zulipterminal/model.py
These are very small changes:
* one to fix #219 based on discussion there, and after the combining of the `register` calls
* another to actually use the `Model.event_types` in both potential calls to `register`, as intended
=> Ensure Gravatar=True & combine Model.event_types use as originally planned

CHANGELOG.md, tests/conftest.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, zulipterminal/ui.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
Main feature: adjust styling in user-list to align unread counts and indent slightly, in line with left column.
Additionally:
* some renaming/removal of internal variables in ui.py
* tests for `show_left_panel` and `show_right_panel`
=> Right panel count alignment and tests

setup.cfg, tests/cli/test_run.py, zulipterminal/cli/run.py
The CLI (run.py) code is currently completely untested. I initially started with some 'black box' testing by running it on the command-line using Popen, but that severely limits the ability to mock. Instead, I've slightly adjusted the function signature of `main` and `parse_args` to explicitly pass in either specific options (for testing) or `sys.argv`, enabling things to broadly still just work with `setup.py`.
The latter two commits then add tests for -h/--help and connection failure respectively.
The main intent here is to enable further (and indicate examples through existing) tests to be added based on these.
This does reduce the code coverage, since it adds `cli/*` back into the coverage being checked, though not by much.
=> Add preliminary CLI tests

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/buttons.py
This continues some of the previous simplification of inheriting from `TopButton`, and extends it for `StreamButton` and `UserButton`. This dramatically reduces the duplicated widget code, which was clear when adding the 'truncated text' code, at the slight code of adding some parameters for the 'prefix character' (bullet, '#', 'P', etc, which can be colored), accounting for muted counts, and overall coloring (as per UserButton). I can see this being useful to easily specify eg. different icons for home/starred etc in future if go choose to go that way, though the motivation at this point is to simplify.
**NOTE** The last commit I am a little less sure about, and would appreciate feedback on. It ensures that a click and pressing `ENTER` do the same thing; currently a click on a button …
=> Refactor Buttons by extending general features into TopButton & inheriting 

tests/model/test_model.py, zulipterminal/model.py
This partially covers the work started in the not-merged #207, in smaller blocks, making it easier to cover the read-message-flags case from this improved point.
This:
* generalizes the method (including name) to deal with all message-flag updates
* generalizes the method internals to work with a general flag-to-change text
* extends the handling to cope with multiple message ids
* ensures we fail fast if we receive an (unhandled as yet) request to flag 'all' messages
=> Starred update generalization

tests/cli/test_run.py, tests/config/test_themes.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py
This work arose out of observing users use the older/incomplete light and blue themes. Hence
* the first commit checks whether themes are complete (have all styles) for the CI; two are currently marked as incomplete, which causes them to be expected failures (and so OK, for now)
* the addition of `complete_and_incomplete_themes` (2nd commit) allows `run.py` to determine complete themes at runtime, and consequently give feedback (a WARNING) on potential quality issues which might be seen
Other than those explicit changes, this includes quite a few other changes, and tests, including
* tests for `in_color` (introduced recently)
* extension of `in_color` to other colors (including yellow, subsequently used for the added WARNING
* add a simple `all_themes` method to `themes.py`; this is …
=> Test theme completeness

CHANGELOG.md, tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
In the middle of working on another branch, I noticed that going to the `test here` stream on chat.zulip.org caused a crash, due to an empty message content - which is of course rather rare. Possibly even the web client will not send empty messages by default?
In any case, this PR avoids a crash, adds a test case, and amends the CHANGELOG ready for the next release.
=> BUGFIX: boxes: Avoid crash in soup2markup with empty content/soup.

CHANGELOG.md, zulipterminal/cli/run.py
This works on MacOs and Linux.
@neiljp I don't think we need to display warning as this works without fail with urwid. If the user still is seeing question marks, it might be due to different problems like one of those double width problems or terminal input-output stream being manipulated or being modified before reaching urwid by terminal.
=> run: Set encoding to 'utf-8' at the start.

README.md, tests/ui/test_ui_tools.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/ui_tools/views.py
@rishig How does this look like, reordering/naming, based on what you said before?
We can discuss further on #z-t, but I was reading it recently and these where some more obvious improvements (at least to my eye):
* reordered/clearer/consistent help text
* remove help-specific 'exiting'
=> Improve/reorder help for shortcut keys & remove QUIT_HELP

CHANGELOG.md, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
Currently these keys only work from the central panel, but I feel these should be narrowing keys which work from anywhere in the app.
I moved the relevant `Controller` calls from the `MessageView` and made it change focus to the messages.
CHANGELOG also amended.
=> Allow 'P' and 'f' keys to work from side panels

zulipterminal/ui_tools/views.py
c HotKey used to crash zt when used in streams
with no previous messages. c now calls stream_box_view
while opening footer and sets name to stream name.
Fixes: #247.
=> view: Fix support for HotKeys in new streams.

CHANGELOG.md, tests/conftest.py, tests/ui/test_ui_tools.py, zulipterminal/config/themes.py, zulipterminal/ui_tools/buttons.py
These 3 fixes comprise fixes for issues that have been bugging me a little, two of which were mentioned by @rishig and itemized in #225.
To summarize:
* Use a white text, rather than 'light magenta' for selected buttons - this seems much clearer (in default/gruvbox)
* Solve the blinking cursor issue by placing the cursor beyond the text
* Set the background of stream icons to be the background color, and icons themselves as 'bold'
The last change should improve the gruvbox theme (@rht), though looks a little strange on the light/blue themes since they don't have as good contrast - and previously this was always a black background.
These should be rather straightforward good fixes, but any feedback would be appreciated :)
=> Improve blue highlight contrast, remove blinking cursor & fix icon background

.gitignore, Pipfile, requirements.txt, setup.py, zulipterminal/core.py
This deletes the queue(deregister) before shutdown(^C) of the ZT.
Fixes #241
=>  Delete the client queue before shutdown

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
I noticed while browsing the #**test here** stream that some messages were rendering as blank. I quoted the message, which showed the original (quoted) source message; these were just image URLs.
When updating the soup2markup code previously, I had included these in the group of tags handled a certain way, but was not sure how to handle them.
* For 'refs', I'm still not sure, but for now I think we should just show them
* For image urls, the other commit now identifies if a link contains an img with the same src as the href, which shows the link just as the text, using existing code.
This shouldn't be a controversial merge, but certainly open for review :)
=> Improve inline item rendering

CHANGELOG.md, tests/ui/test_ui_tools.py, zulipterminal/helper.py, zulipterminal/ui_tools/views.py
This improves the situation regarding unread-counts, so that if you receive a message from a user who is in the right-panel, a count appears next to their name properly. It should also slightly improve stream unread counts, if there was a conflict present, which I'm not sure there often would be.
The second commit avoids the issue where a message sent by yourself would increase the unread count, which I'm fairly sure was also a bug.
See the commits for a little more detail.
=> Unread counts: Introduce UnreadCounts TypedDict & avoid mixed indices.

CHANGELOG.md, README.md, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/ui_tools/views.py
This was inspired by a suggestion from @rishig; where possible using the same key again can make things simple - here we retain the ability to exit the help menu with 'esc' (at least for now) but allow '?' ('HELP') to also do so. This also allows the help menu to be simplified slightly.
Changes spread across multiple locations:
* allow '?' to exit the help view via 'HELP' key (views.py)
* 'HELP' key description (keys.py & README.md)
* title of Help view (core.py)
* add note in CHANGELOG.md
=> help: Allow '?' to show/hide (toggle) help view, not just show it.

README.md
I've attempted to improve/update the notes again, including broadening the details of virtual environments and   adding a native pip (as opposed to pipenv) install, to give people an alternative option.
Re that last point, I'm happy to move the pip notes to after pipenv, if that would be preferred.
I'm still interested in adding tox support so we can run multiple environments locally like on Travis, but that would be yet another alternative :)
=> Improve Installation notes for users & developers

zulipterminal/core.py, zulipterminal/ui_tools/views.py
Define the height attribute (default to the number of key bindings) and
remove the bottom line character.
=> Compact the HelpView.

CHANGELOG.md, zulipterminal/core.py, zulipterminal/ui_tools/views.py
This is a quick follow-up to the help menu observation and contribution by @matrixise in #298 and #297.
This PR:
* Removes side/top spaces
* Sets alternating background colors (using 'bar' style for now)
* Adjusts the menu height to be between (the minimum) of 3/4 window height (rows), and the number of help menu actions
The latter does increase the menu height slightly (it was set to 1/2 in #298), so any feedback through testing would be good.
Tagging @amanagr & @rht who also gave feedback on the PR by @matrixise.
=> Improve help menu: compact further, style lines, adapt height

zulipterminal/cli/run.py
This PR is a small refactoring of `run.py` that was proposed some time ago on zulip chat. The main idea was to eliminate unnecessary recursion from `parse_zuliprc`, but I've also changed error handling a bit.
List of changes:
– remove an unused import
– remove recursion from `parse_zuliprc`
– narrow down caught exception types where possible
– fix a bug where `fetch_zuliprc` would throw an exception because of incorrect variable assignment (line 95)
– handle errors in the actual parsing of `zuliprc` (e.g. when the path passed as an argument led to a random file or a directory)
– when a `parse_zuliprc` call is interrupted by `Ctrl+D`, don't delete the `zuliprc` file if it has been created. This was briefly discussed on chat. A situation where `zuliprc` has to be deleted, i.e. when …
=> Error handling and other small fixes in run.py

CHANGELOG.md, README.md
This incorporates some of the recently-raised points with some tidying & reorganising; briefly:
* Add `flush=True` (@sumanthvrao) to debugging tips, and add subsections
* Simplify/clarify the pipenv setup for development install (@punchagan ; not using pip3 yet, could do?)
* Move the 'edits aren't affecting zulip-term' section into debugging tips
* Move the remaining 'troubleshooting' section above the development section
* Make the 'Contributor guidelines' the start of the development section
The final result looks like this:
https://github.com/neiljp/zulip-terminal/tree/dev-docs-improvements
=> Further README improvements

tests/cli/test_run.py, zulipterminal/cli/run.py
Print the version of the terminal client, also prints out the git short hash if on a git version.
Fixes #280
=> cli: Add functionality to check version from command line. Fixes #280

tests/model/test_model.py, zulipterminal/model.py
Set the flags for the received messages from the `event` instead
of initializing them with empty list.
This marks the messages sent by user as read too.
=> model/append_message: Set proper flags for received messages.

Pipfile, requirements.txt, setup.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This moves ZT to using the specific API calls available in the latest `zulip` package; this makes the code more concise.
We do need to depend upon a later zulip package, since there was a bug in an earlier version which meant that one of these changes didn't work.
I've also renamed two methods for clarity:
* `update_flags` -> `mark_message_ids_as_read`
* `update_presence` -> `_start_presence_updates`
The latter has additional documentation on what I think is the likely route to improve the way that presence updates occur.
=> Model: rename 2 methods, use client API

zulipterminal/helper.py
This effort started as an attempt to simplify `set_count`, and in doing so the code looks a lot clearer.
Some of these commits could likely be combined, but since this code isn't well-tested in CI then I've left them separate for now to enhance clarity.
Two commits should address apparent bugs:
* Don't add counts to the total if it's muted
* Only reduce unread counts if the server reports success on marking messages as read
=> Improve unread counts (refactor/simplify & fix few bugs)

CHANGELOG.md, tests/ui/test_ui_tools.py, zulipterminal/ui_tools/buttons.py
Fixes #273.
Add tests.
Add note to CHANGELOG.
@n-cc I placed this in a pull-request to make things easier :)
=> Support #fff style for stream colors on older zulip servers

Pipfile, requirements.txt, setup.py
The latest tornado is now 6.0, which doesn't support python 3.5.
Rather than remove snakeviz or only install in some python versions, this requires installation of the earlier tornado version, which is still available.
=> requirements: Explicitly install tornado ~5.1 for snakeviz on py 3.4.

zulipterminal/cli/run.py
Following some confusion over pre-existing use of 'Zulip Realm URL', this moves to use the form used in the desktop app, namely indicating 'Organization URL' and giving some examples.
=> Clarify Organization URL (was Realm URL) with examples.

zulipterminal/model.py
This is a follow-up on some earlier refactoring I worked on, inspired by a bug-report by @omi10859 on the #zulip-terminal stream recently. This is not directly targeted at this bug, but brings all the event-registration code into one method, which was previously only used for re-registration, with common error-handling too. This also adds retries for re-connecting, since previously if this failed we just raised an Exception (leaving the thread boundary!)
=> Model: Consolidate register calls & improve error handling

zulipterminal/model.py
This fixes #334 : previously reaction couldn't have been undone, unless it was added in current session of zulip-terminal.
=> Undoing thumbs-up reaction now always works.

CHANGELOG.md, zulipterminal/model.py
In Model.append_message we now split the recipient email string from the
narrow into a list which is mapped to frozenset of user-id, instead of
previously assuming we could look up the recipient string as a single
recipient email.
CHANGELOG.md updated.
=> BUGFIX: Fix sending to multiple recipients when narrowed.

zulipterminal/ui_tools/boxes.py
Implements #147 
The hint is displayed in the footer where random hints are displayed. The key suggested is `Fn + Alt` on OS X and `Shift` elsewhere. `Fn + Alt` [worked for many people](https://github.com/mitmproxy/mitmproxy/issues/597#issuecomment-163819671) in another project using Urwid. `Shift` works for me on Linux but not on OS X.
=> Display a hint when the user tries to select text with mouse

zulipterminal/core.py
**Steps to repro the bug**: 
* Send a test message to yourself (PM)
* Go to All Private messages narrow.
* Use z on any message with self.
The narrow does not change to message with self instead switched to All messages.
**Commit message**: 
When 'z' hotkey was used on in the All private messages
narrow, on self messages, it did not switch narrow
to PM with oneself. We now handle this logic explicitly.
=> core: Fix action of 'z' on self-messages.

.travis.yml, CHANGELOG.md, Pipfile, README.md, requirements.txt, setup.py
Python 3.4 is now end-of-line, and dependencies (those below & requests)
are now expected to support 3.5+. This simplifies things as below, but
also may enable removal of old compatibility code and new features only
available in python 3.5+.
Removes:
* testing 3.4 in Travis CI
* labelled python version support in setup.py for 3.4
* pinning of pygments & tornado package versions in setup.py/Pipfile/requirements.txt
* need to explicitly install typing package in setup.py/Pipfile/requirements.txt
Also updates reference to 3.5 in README.md, and adds to CHANGELOG.md.
This is a first stage towards #360.
=> requirements: Remove support for python 3.4.

zulipterminal/core.py
In some terminals, 'ctrl 4' generates 'ctrl \', which sends a quit
control character, which abruptly exits zulip-terminal.
This is resolved by adding it to the list of keys to be ignored
externally and handled by urwid, as is already done for 'ctrl c' and
'ctrl s', via tty_signal_keys.
=> bugfix: Avoid crash on 'ctrl 4' by ignoring quit character

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This makes a little more space for the message text, but would appreciate what people think compared to master after the merge of #328.
=> boxes: Reduce message padding after introduction of (EDITED).

zulipterminal/ui.py, zulipterminal/ui_tools/views.py
This is something of a follow-up to the recent UI changes in #T408 to keep the columns separated, where it minimized the lines and made the UI more columnar, but now perhaps became a bit less clear which elements were 'titles'.
This small commit emphasizes the Streams, Messages and Users titles, by using a different line around it.
=> ui/views: Set title lines in columns in bold

tests/conftest.py, tests/core/test_core.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_utils.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/utils.py
I mentioned making this change a while ago and it seemed to receive a positive response, so I've just fixed the tests and made some other minor adjustments which enable the line length to match our standards.
This PR makes the Index data a lot easier to `git grep` for, when following through the code, as well as being more descriptive, including in test fixtures.
The commits are broken into:
* One commit to update the 3 simple data structures and tests (ie. just sets of integers)
* Two renaming/refactoring commits to reduce verbosity (in preparation for...)
* One commit to update the 3 other more complex data structures, and tests
* The last commit to adjust the ordering and comments for clarify
The ordering is perhaps a little arbitrary, but I think it's important to group the 'indexed …
=> Refactoring: Improve index naming 

tests/core/test_core.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
In reviewing early commits of #382 I was examining the use of 'caption' on the buttons/boxes.
This PR is an attempt to make this clearer, and lead in to the (now) early commit of #382.
I would particularly be interested in @amanagr reviewing this, to give insight into whether this is moving away from some original design or not - though it seems cleaner to me :)
I think it may be worth examining the objects/types we pass to the narrow methods; the duck-typing works fine, but at least renaming of the 'button' parameters to the narrow methods, would definitely help developers reading the code understand that boxes can be passed too (for example)?
=> Refactor extra captions to streams and topics

README.md, tests/ui/test_ui_tools.py, zulipterminal/config/keys.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This is an attempt to work upon the remaining concept in #408, namely to improve the consistency between the search boxes.
Since each area (streams, messages, users) appears clearer with the 'bold headers' of #413, it seems more feasible to reduce text duplication in the UI and simplify the search text to the minimal form used in the message search box. This PR first extracts the common locations for that text, then:
* unifies the documentation/help to the title of the right panel (Users vs People)
* simplifies the text to just 'Search:' for the Streams and Users areas
* Adds shortcut key 'labels' to each search box, as suggested by @rishig (?)
The last change could be diverted to another PR with similar changes, but it's search-box related and easier with shorter search-box text, so …
=> Search box improvements

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This PR comprises two changes to improve search code, that I first saw some time ago:
* Simplifying locking using contextmanagers
* Tidying up the searching code, which used a lot of copying, using list comprehensions
The first needs a little change to the tests; the latter looks cleaner to me, but also seems a lot faster, at least on chat.zulip.org - possibly due to the number of users.
The improvement in search speed exposes a small bug - which I don't believe is caused by these changes.
=> Refactor locking & search filters

zulipterminal/core.py
Possibly fixes #456.
@amanagr FYI :)
=> core: Avoid writing newline to stdout after UI has loaded.

zulipterminal/ui_tools/buttons.py
With 0b8052b we moved the logic to 'mark button
as muted' from TopButton into respective button classes
(StreamButtons).
However, we forgot to update the same call for muted TopicButtons.
This patch fixes the same.
=> bugfx: buttons: Fix marking 'M' in muted topics.

tests/model/test_model.py, zulipterminal/model.py
Each element of `self.muted_topics` is a two element list containing stream_name and topic name. This patch fixes the `is_muted_topic` helper which checks if a given topic of a stream is muted or not.
Type annotations added.
Tests amended.
=> bugfix: model: Fix is_muted_topic helper using list instead of tuples.

tests/model/test_model.py, zulipterminal/model.py
Previously we just indicated private messages (PMs) were directed to 'you', even if it was a group PM. This commit updates this to use a comma-delimited list of full names.
Tests extended to include title parameter.
(The first commit is a test refactor to enable the test extensions associated with the main commit.)
=> Include all recipients in group PM notifications

Pipfile, requirements.txt, setup.py
Other than upgrading to a later pytest version, this commit also
resolves an issue with Travis, avoiding a need to specify an upgraded
attr package explicitly since this pytest depends on a later version.
Note that this can cause two warnings to be output by pytest re `inspect` being used in a deprecated way inside `urwid`, but I'm not sure there's much we can do here for now.
@amanagr @sumanthvrao The latter issue is causing failures in PRs right now, hence the high priority.
=> requirements: Upgrade pytest from 3.4.2 to 3.10.1.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
Class `UsersView` wraps up incoming `users_btn_list` in a
SimpleFocusListWalker object. It is not necessary for the
incoming data to be wrapped in the ListWalker as well.
Tests amended to support changes.
Tested:
Previous behaviour of
* User search
* Updating user list at 60-second intervals 
are intact.
=> views: Avoid wrapping users_btn_list in SimpleFocusListWalker twice.

Pipfile, requirements.txt, setup.py
The new zulip library version allows catching of `ZulipError` in an
additional case, removing some cases where a requests exception was
thrown directly into zulip-terminal.
This avoids an uncaught exception, in cases such as being connected to a
network but not routed, such as if not signed in to a wifi router.
=> Upgrade zulip to 0.6.1, avoiding uncaught SSLError

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This fixes a few outstanding issues in link rendering:
* Don't render extra copies of images/refs provided by the server
* Render simplified links (where text & link match) in the link style
* Improve handling of relative links, by using `urlparse` and `urljoin` to determine them & prepend the server URL
* Ensure that if we get a relative link which matches the actual text, we also simplify that rendering (the server simplifies the URL; we want to ensure the full link+text is simplified)
Tests are updated & added.
=> Improve link rendering

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This is a fix for #470, has tests, and works functionally for me. Feedback welcome.
I propose that the extension ideas in #470 are placed into other issues, for things such as any styling improvements and potentially dynamic date changes as with the webapp.
=> Indicate message year, when it is not the current year

zulipterminal/cli/run.py
Issue:
When trying to login to the Zulip terminal, the error message being displayed after entering the wrong email or password is "Username or Password Incorrect!" but the user is never asked for a username. 
Fix:
Rephrasing the error message in `run.py`
Screenshots:
Before:
After:
=> run: Rephrase the login screen messages.

Pipfile, requirements.txt, setup.cfg, setup.py
This is a replacement/extension for @amanagr's idea in #455. pytest was partially upgraded in 14c9161 already. Since #455 was opened, 5.3.1 is now available (cf 5.0.1 in #455 ).
Upgrading shows two types of external warnings:
* `urwid` uses some 'inspect' calls which are deprecated (since last upgrade to 3.10.1)
* `pytest-pep8` doesn't set up some kind of 'hook' to register a marker
To avoid confusing users with these warnings about external code, this commit works around
the existing and new issue by adding a `filterwarnings` entry for urwid, and explicitly
mentioning the pep8 `mark`, both in `setup.cfg`.
=> Upgrade pytest from 3.10.1 to 5.3.5 (latest).

.travis.yml, Pipfile, README.md, requirements.txt, setup.cfg, setup.py, tests/conftest.py, zulipterminal/model.py
This is intended to be a step towards updated PEP8 linting, as now
provided by pycodestyle.
Other than moving to a more maintained and current linter (pycodestyle
vs pep8), using a separate linter outside of pytest makes it more obvious which aspects
are failing (tests vs pep8 linting) and reduces the need to run it in
every test run - including each version of python on CI. It also allows
the linter to be run consistently in editors more frequently (if
desired), as it runs fairly rapidly.
Locally this broadly just splits the time taken to run, with pycodestyle
taking ~3s.
* Update dependencies (pytest-pep8 -> pycodestyle)
* Add pycodestyle configuration to setup.cfg
* Remove pytest-pep8 configuration from setup.cfg
* Minimal changes to two files to show consistency
* Explicitly add PEP8 …
=> tools: Use pycodestyle in place of outdated pytest-pep8.

.travis.yml, setup.py
* Use `pip3` in travis instead of `pipenv` - this alone reduces runtime significantly
* Split linting and testing dependencies from general 'dev' dependencies in `setup.py`, allowing unnecessary package installation to be avoided in travis
* Now that jobs run faster individually, it's practical to set up linting in separate jobs, making it easier for developers to see what CI aspect failed
* On each platform, first install the package, then install testing packages for running tests; this is a partial fix towards #181.
I merged #502 pretty quickly so that this would be easier to discuss/review. However, I think the increased speed from pip over pipenv makes this a pretty clear improvement.
=> Improve CI speed & effectiveness

tests/ui/test_utils.py, zulipterminal/core.py, zulipterminal/ui_tools/utils.py
This is a more straightforward version of #449, splitting things up to make the main refactoring and some of the implicit changes more obvious.
This version also provides a parameter to the extracted method to specify the `anchor` for the narrow, which clarifies when message focus is retained on changing narrow (if possible).
The last commit then extends the message focus retention to all-messages and all-PMs narrowing; this is a specific change in behavior, but with this refactored version it should be more obvious what is happening.
NOTE: I've not changed the behavior for starred messages, as it didn't seem to be an issue - but we should investigate this.
NOTE: I may extract the `stream_id` setting into the model, but I think this is clean enough to merge now.
=> Refactor & improve narrowing logic

README.md, tools/lint-all
Adjust development section of README to indicate use of tools/lint-all for linting, rather than the separate tools.
=> tools: Add tools/lint-all script to simplify local linting.

zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/utils.py, zulipterminal/ui_tools/views.py
This expands use of the existing `Message` type alias for message data.
In some cases, this replaces broad `Any` typing, and in others is a more explicit (but equivalent) substitute for `Dict[str, Any]`, which is the current type of `Message`.
This exposes one case where we cannot make this substitution without refactoring, so I've added a note.
=> Type Annotations: Use Message type alias consistently

zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
I'm pretty sure we can make these changes with no ill effect, and give much cleaner code with less noise as a result.
There is one outstanding parameterised use of `super(...)` in a multiple-inheritance case for the custom `Walker` class implemented by @amanagr. It'd be good to know if we can tidy that too, but I've not explored it in detail.
I plan to follow this up with some improved typing for the `keypress` and `mouse_event` methods, but there are a few limitations there (any news on that front, @amanagr?)
=> refactor: Simplify unnecessarily complex super(...) calls.

zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py, zulipterminal/urwid_types.py
This PR attempts to improve the consistency of these methods, based on their types as defined in urwid.
Currently this defines `urwid_Size` rather loosely, but I wanted to set some kind of standard so that when we make additions then contributors can compare to the existing code and see this. The type alias can always be changed later if we want to.
@amanagr The `FIXME` in `ui.py` is the issue I was referring to you a while back.
=> Type annotations: Improve keypress and mouse_event signatures

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This commit fixes the stream and topic search to find if the search query is a substring of any stream/topic.
Fixes #509.
I'll proceed to add the tests if the implementation looks good to you, @neiljp.
=> views: Fix stream and topic search.

tests/model/test_model.py, zulipterminal/model.py
This PR first adjusts the error handling in functions used by `ThreadPool`s in the model, allowing for a reason to be passed back rather than just a boolean. That in turn allows for reporting of why an error has occurred to the user; initially this is simply for the first connection attempt to the server, which can diagnose rather useful situations such as incorrect API keys.
Tests are amended for the refactor, and a test added for the example case of an incorrect API key.
=> Report reasons for initial connection failure

tests/ui/test_ui_tools.py
Updated hard-coded keys used in STREAM_MESSAGE, REPLY_AUTHOR, and REPLY_MESSAGE with their respective key parameters.
This solves a part of #533.
=> tests: Parameterize hard-coded keys used in keypress tests.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This resets search box text whenever the user presses `esc` key to clear the search. The text is replaced with its appropriate search text along with the key required to trigger the search and amends the tests.
@neiljp It was not working as expected for topics as well. I have added a patch for that.
GIF: 
[![asciicast](https://asciinema.org/a/309148.svg)](https://asciinema.org/a/309148)
Fixes #536.
=> views: Reset search box text when 'esc' is pressed.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
While not visible in the default theme, in the light theme the two parts of the
date are separated by a gap, due to how the optional year feature was
added as an extra column. By merging the columns and explicitly adding
spaces this now displays more cleanly and appears as one block of text.
Tests amended.
=> boxes: Merge date/time and optional prev-year fields to improve styling.

zulipterminal/config/themes.py, zulipterminal/ui_tools/buttons.py
This resolves one aspect of #544, by separating out a style for unread counts from that used for idle.
This in turn allows an improvement in the styling of unread count text, which has been a blocker to improving the user-list styling in the light and blue themes.
Given the small code changes, for review purposes I'm more interested in how this looks compared to master for people on different platforms.
I have a followup to improve the blue theme further, both along the same lines as #553 and now including lightening the user list (if we want this).
=> Themes: Separate unread count and idle styles

zulipterminal/config/themes.py
I've noticed this before, but my feeling is that it's confusing when moving between the side panels and the message list, that the selection is different.
I explored matching them in the light theme in 2c211bb, and I think that's an improvement.
This PR updates the blue and default themes, not yet touching the gruvbox theme. I also adjusted the unread style, as that's important to show a clear distinction between unread/active/read.
Any thoughts on this approach in general, and also if you think it's good, of how to approach it in gruvbox, would be great to hear.
=> Improve consistency of selection styles

zulipterminal/helper.py
I got this Idea after looking at #548 since our `set_count` function is particularly complex (not so well structured code). 
The function is now separated into out into set_model and set_UI. Though these two are not completely uncoupled, this should be a good start along those lines.
=> refactor: helper: Separate setting counts for model & UI.

zulipterminal/ui_tools/boxes.py
I was diving into this code to look into the `:crossed_fingers:` vs `:fingers_crossed` situation and noticed this code could be cleaner.
This PR is mainly refactoring to make this clearer to read and more pythonic.
However, partly as a result of the refactoring (or vice versa) this PR adds "unstyled spaces" between reactions - this is particularly noticeable for messages such as in **#announce** with lots of reactions (and of different types), and clearly associates the number with the reaction itself (particularly when the message is selected). The other side effect is that there is also no trailing "styled" space.
=> Message reactions: Add spacing and refactor

README.md, zulipterminal/helper.py
The `osascript` command takes in the notification sound as an
extra parameter and without it doesn't have a default sound.
We set an env variable here to tell zt to play a
sound when it receives a notification.
README has been updated to describe the changes needed to
set the env variable.
=> README/helper: Support notification sound for OSX.

setup.py
Following discussion around [this conversation](https://chat.zulip.org/#narrow/stream/127-integrations/topic/PyPI.20release/near/853887), this inspired the following suggested changes in this commit:
* The license is set in the trove classifiers already, and matches the
LICENSE file, so is not needed as a separate setup key.
* Zulip is typically capitalized, so use Zulip rather than zulip in
description.
* Use 'Zulip Open Source Project' as the author, like other Zulip PyPI
packages.
=> setup: Minor adjustments (remove license, adjust some text).

tests/cli/test_run.py, tests/config/test_themes.py, tests/core/test_core.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py, zulipterminal/core.py
Currently we just run with 256 colors and assume the user system supports that.
This is reasonable to a great degree, but urwid supports palettes from 1 (monochrome), 16, and others too. The first commit in this PR enables specifying color depths of 16 or 256 on the command line, defaulting to 256, which may help with reproducing color rendering issues. The subsequent commit is a minor change which makes the 256-bit stream colors be rendered with a color; I'm open to dropping this commit as we could do something different.
The last three commits extend the first commit to allow running in monochrome, add reasonable defaults in the default theme, and finally overwrite the monochrome settings in all themes at run-time. I can't imagine we'll actually want monochrome themes, which is why I …
=> Improve support for different color depths (16, 1)

tests/model/test_model.py, zulipterminal/model.py
This is a fairly straightforward set of refactors to help with understanding the structure based on names and layout, and may help with future progress in this direction.
Also improves docstrings on various methods.
Tests amended & tidied.
=> Refactor model event handling methods

tests/ui/test_ui_tools.py
This brings minor changes to exit popup keypress tests (previously 'GO_BACK' tests).
* The first and the second commit are renaming refactors to improve consistency (more on this is in the respective commit description).
* The third commit adds command keys to exit popup keypress tests (see #561).
* The fourth commit adds exit popup keypress test for `StreamInfoView`.
Fixes #561.
=> tests: Add command keys for exit popup keypress tests.

zulipterminal/config/themes.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/tables.py, zulipterminal/ui_tools/views.py
This tool automatically upgrades some common early python.
Changes made include:
* removal of u prefix from unicode strings
* remove some excessive uses of set() where {...} is sufficient
* use 'yield from' for spinning_cursor
* remove extra parentheses
Fixes #360, at least to a reasonable automated level at this point.
=> cleanup: Results of pyupgrade with --py3-only --keep-percent-format.

.travis.yml, Pipfile, requirements.txt, setup.cfg, setup.py, tests/config/test_keys.py, tests/conftest.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, tools/lint-all, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
Flake8 covers a lot more coding errors than pycodestyle, including finding unused imports - just as one example. This PR translates the dev and CI environments to use flake8. No documentation should need to be updated, as long as people are just using `tools/lint-all` rather than raw pycodestyle.
The 'barebones' flake8 takes ~6s to run locally for me right now, compared to the ~3s for pycodestyle, but combined with mypy and isort, this isn't as big a proportional change.
This PR removes default installation of pycodestyle (it is installed via flake8, though). We could keep it around as an intentional developer tool, but then we'd need to keep the settings synchronized.
flake8 also has various plugins, which we could investigate further if we go ahead with this.
=> Migrate from pycodestyle to flake8 in CI & locally

README.md
NOTE: Some of this was inspired by trying to simplify and focus the README better, but also include some of the tips we've found recently, such as installing a development version straight from git using pip.
This is mainly a restructuring of text, with a few additions.
* Continue to recommend installing in a virtualenv, but place those
details lower and integrate them with the 'different sessions' note
* Emphasize the main installation command is from PyPI
* Add a way to install current development version from git using pip
* Add that we include some docker build scripts
* Remove the simple 'running' part and 'what it shows when running'
* Turn the zuliprc file text into a 'Running for the first time' section
* Convert the 'example zuliprc file' text into a 'Configuration' section
* …
=> README: Update installation, running & configuration notes.

Pipfile, requirements.txt, setup.cfg, setup.py, zulipterminal/cli/run.py, zulipterminal/ui_tools/boxes.py
This enforces multi-line quoting at this stage, which we have mostly been consistent with already.
Regular quoting is a little less consistent right now, so I've not enabled that check. There is some argument for keeping single quotes for short elements and double for longer, but I favor sticking with one type for regular strings if we can - it makes searching for string (vs variable names) much easier.
=> Start to enforce quoting styles using flake8-quotes

Pipfile, requirements.txt, setup.cfg, setup.py, tests/config/test_keys.py, tests/core/test_core.py, tests/model/test_model.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, tests/ui/test_utils.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This commit slightly adjusts the layout of many files, with other minor
adjustments to:
* combine quoted strings on adjacent lines
* simplify some conditionals using .get()
* return directly the result of boolean expressions
* generally adjust indentation/ordering for readability & linting
An example of the change in acceptable behavior is from (accepting W503, ignoring W504):
(foo and
bar)
to (accepting W504, ignoring W503):
(foo
and bar)
While both are acceptable according to PEP8, the latter is now recommended:
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
=> linting: Switch to check line break before binary operator (W504) & for presence of continuation characters

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
Tests amended & added to cover new behavior.
Follows style of 91b1ea471 by telescopic <vigneshsuresh1775@gmail.com>, but for topics rather than streams.
=> bugfix: views: Ensure focus returns to previous topic after search.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This change:
* makes it clearer when markdown text is recognized as bullets
* saves space by removing extra lines that are in the html
Tests amended.
New tests added for changed code, to ensure newlines removed:
* between ul and li elements
* between li and p elements
---
To see a good example of the reduction in newlines this makes, have a look at:
* simple bulleted elements in eg. #**test here**
* the bash++ topic in #**learning** (there were extra newlines *after* a bullet, before text)
A side by side comparison makes the difference very obvious.
The bullet characters make it clearer when a bullet is used, since `* foo` previously appeared like a bullet, but wasn't always recognized by the markdown parser eg. depending on indent, so wasn't always obviously rendered differently.
Note …
=> Use bullet character in list & remove newlines.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
Previously the focus was moved into the search box part of the Frame
header, but the header itself was not focused. The search worked, but
entries remained selected in the topic list (body).
Test added.
=> bugfix: TopicsView: Focus Frame header (search box) on search.

tests/cli/test_run.py, tests/config/test_themes.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py
This implements the renaming of themes as discussed in the 'Rename default theme' topic.
Also included is an 'alias' table, to allow the old names to continue working, at least for now.
=> themes/run: Rename themes & add compatibility aliases.

zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
Previously if notifications were enabled, but we cannot find the notification executable, then a traceback appears over the UI - I only noticed this since I copied a zuliprc file to another machine where the notification commands weren't available.
This small commit fixes this by wrapping the subprocess.run in a try/except block and logging FileNotFoundError exceptions, currently to `debug.log`.
**NOTE** This fixes the issue as it stands, but could spam the debug file and not be very obvious. I've noted some alternatives in the comments; we could merge this now to avoid the messed-up UI and work on the method in another issue/PR, or decide how best to approach this.
=> Don't corrupt screen if notifying fails; indicate to user once instead

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This is a followup to #634 - not only does it render numbered lists, but since it handles them explicitly then we can remove extra newlines in that case, as we did in the other PR.
Numbering starts with the first number specified in the list, as per the Zulip revised scheme:
https://github.com/zulip/zulip/blob/master/docs/subsystems/markdown.md#lists
soup2markup now has a kw-args parameter 'state', in which a 'list_index'
entry is set by the ordered-lists code to have an index, incremented
through each list item, starting at the value specified in the 'start'
attribute of the html ordered list (ol).
Tests added.
=> Render ordered lists

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This applies the styling in the message-view which indicates when a search is in progress, to the streams, topics and users views - making it visually clearer when the values shown in the view (being listed) are filtered, ie. a search result. This goes partially toward fixing #552.
GIven there were no tests for the `PanelSearchBox`, modified for this feature, this PR also includes a commit adding tests for this class first.
=> Indicate panel searches in progress

zulipterminal/config/themes.py, zulipterminal/ui_tools/buttons.py
I noticed this while testing the thin-colorer-barbranch.
Prior to this commit:
* narrow text (excluding topics) was plain, with topic names in
standout; this commit broadly inverts this, setting non-topics in
standout and topics in bold, to produce the expected visual ordering
* stream '#'/'P' marks and unreads were visually undistinguishable from
the stream name; this commit sets these all as bold
=> Improve monochrome rendering of narrows & streams.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
This fixes #671, which is reproducible by resizing the window to be very narrow and noting the 'blank' headers that appear where there is a change in recipients.
An additional commit is included, which improves the spacing between the header text and the new lines/bars, both fixing an existing bug (for PMs) and ensuring a space is shown in the narrow-window situation.
=> Ensure recipient headers are shown in message list

tests/core/test_core.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, zulipterminal/core.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This was previously partially encapsulated in WriteBox for local use,
but this wraps all functionality with access via the Controller using:
* is_in_editor_mode()
* enter_edit_mode_with(editor)
* exit_editor_mode()
* current_editor()
This then allows further tests for this and refactoring, as well as being more descriptive.
=> Encapsulate editor/editor_mode

tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
The intention is to extract and generalize duplicate code to expedite the popup creation process.
Along with that, it tidies up popups, that derive from PopUpView, by calculating their required width and height based on the content instead of using hard-coded values.
Tests amended.
As a side effect, fixes #654 and #658.
=> views: Refactor popups to expedite the popup creation process.

README.md
Update the command to install development requirements using pip.
Zsh does not match expressions unless surrounded with quotes.
Thus, executing the command without quotes causes it to fail.
=> README: Update pip install command.

.gitlint, README.md, docs/FAQ.md, setup.py
The changes should be self-explanatory, but basically this shows the information determined to date via #662 into a new FAQ file containing the previous 'troubleshooting' text.
This also adds `project_urls` metadata to `setup.py`, which adds them in the sidebar. A preview of this can be seen at https://test.pypi.org/project/zulip-term/0.5.2a2/ (see project links in the side bar)
=> Split FAQs, add list of terminal emulators, add project_urls

zulipterminal/helper.py
Unread count data from the server may include that for unsubscribed streams, which currently are not indexed.
Fixes #694.
=> bugfix: helper: Avoid updating unread count for unsubscribed streams.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
The first commit is a refactor that extracts `streams_view_divider()` from `streams_view()`. 
The `streams_view_divider()` is used in the second commit, in `update_streams`, for inserting a divider between search results.
Fixes #577.
=> Visually separate pinned and unpinned streams while searching

tests/model/test_model.py, zulipterminal/core.py, zulipterminal/model.py
This PR fixes an update message bug which is caused by two different sources.
1. When a stream is not fully loaded, `Model.found_newest` is set to`False`. Now if a message is received on other streams which are fully loaded, it won't be appended to the view due to `found_newest` state. This is fixed by maintaining found_newest for each narrow.
2. On switching between narrows, `found_newest` is set to `False` in the `Controller`. This obviously prevents appending of new  messagea in the narrow, unless `down` is pressed.
Similar bugs are present (now fixed) for sending messages, since they too use the same `Model._handle_message_event` for adding messages to the view.
=> Fix message updating bugs due to found_newest

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
Updated generic_autocomplete along with its autocomplete_mentions/streams to provide typeahead even when there are some characters before their respective trigger character.
Fixes #541 and #448 (partially).
=> boxes: Improve trigger sequence for generic_autocomplete

tests/core/test_core.py, tests/model/test_model.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/views.py
The motivation for this PR started as an exploratory migration of the `msg_list` and `msg_view` attributes of the `Model` into a more appropriate location - the `View`. These variables have stuck out each time I look at the model due to their UI focus, and that they're initialized to meaningful values outside of the `Model`. One is used in some model methods, but similarly to `set_count`, these are cases where there are model and view changes, which can be split - and so the UI ones can hopefully be migrated into the `View` after this change.
Some less directly connected refactoring commits are included: the first three are not strictly related, so could be merged separately or first, but should be small or separate to understand and review.
The last 4 commits are the thrust of the PR:
* …
=> Refactoring focusing on tidying/migrating msg_list & msg_view

docs/getting-started.md
These links were out-of-date against the recent documentation updates that were merged.
=> docs: Update obsolete relative links in getting-started.md

tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This PR adds checkboxes to `StreamInfoView` for toggling muted and pinned settings for streams.
There are two parts to this PR and a bunch of minor refactors:
**1. Add support for muting** - We already handle mute events, so all we have to do here is add a checkbox that will toggle mute status.
**2. Add support for pinning** - First support for pinning events are added, then a checkbox is added to `StreamInfoView`.
=> Toggle stream settings

README.md, tests/cli/test_run.py, tests/core/test_core.py, tests/ui/test_ui_tools.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py
This adds support for configuring footlinks view in MessageBox (defaults to 'enabled') via zuliprc.
README updated with instructions.
Tests amended.
=> Support footlinks configuration via zuliprc

Pipfile, docs/FAQ.md, requirements.txt, setup.py
This sets dependencies as generally more flexible:
* 2.1.x (x>=1) for urwid, to allow bugfixes
* '>=' current latest versions for zulip, beautifulsoup4, urwid-readline and lxml
Feedback welcome!
Note that the urwid upgrade fixes 256-color support for at least `mosh` and `urxvt`, is likely to do so for `Terminal.app` (macos) and may for others too. If anyone tests those and has feedback for this in particular, we can update the `FAQ` to improve those notes on terminal emulator support :+1:
=> Upgrade core dependencies

zulipterminal/model.py, zulipterminal/ui_tools/boxes.py
Users can manually alter the recipients/stream name, but there is
currently to check in place to ensure validity of these modifications.
This commit checks the recipients everytime the user presses TAB on the
boxes (stream name and recipients for private messages).
=> Check validity of recipients on manual modification

zulipterminal/helper.py
A quick oneliner which hopefully fixes some errors which are caused trying to display an error in the footer, before the view is loaded.
=> bugfix: helper: Check view is rendered before displaying errors.

.gitignore, zulipterminal/cli/run.py
Previously the zulip-terminal-traceback.log file was polluted with urllib3/requests debug messages. This separates these two sources.
In future, we could enable API call logging only in a debug or development mode.
We could potentially do the latter sooner rather than later - thoughts?
=> Split API call and traceback logging into different log files

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This is the v1 that we discussed in [zulip-terminal > Topics on demand](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Topics.20on.20demand/near/967222).
Now, topics are only fetched when they required for the `topics_view()` (for the topic toggle) or for the `_update_topic_index()`.
Tests amended with a few spelling corrections.
Fixes #493.
=> Fetch topics on demand to prevent heavy load on /topics

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
Currently, we use the last segment of a link for this purpose. It works well for links that have an image or a file. For instance,
https://foo.com/image.png gets rendered as image.png, but it does have a few caveats.
This shows the ending for a filename, the domain name for a general link and the relative URL for an internal link.
Test amended.
Fixes #742.
=> Delegate link text for raw links in a better way

.travis.yml, Pipfile, requirements.txt, setup.py, zulipterminal/config/keys.py, zulipterminal/helper.py, zulipterminal/model.py
This requires the PyPy build to be upgraded due to a failure in earlier PyPy versions.
This also upgrades the mypy we test against - this doesn't require any changes, however.
=> Migrate from mypy_extensions to typing_extensions

tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This adds an instance attribute, `time_mentions`, to the class `MessageBox` to log time mentions (with their source text) and eventually show them in `MsgInfoView`.
=> Show time mentions (with source text) in MsgInfoView

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/buttons.py
Currently, logic for updating unread counts after muting/unmuting
streams is present in StreamButton. This commit moves this logic to the
Model.
unread_counts['streams'] has been changed to defaultdict(int) so that it
returns 0 when a stream id is not present.
Tests amended.
Fixes #722.
=> Move unread_count from StreamButton updates to Model.

README.md, tests/cli/test_run.py, tests/core/test_core.py, tests/ui/test_ui_tools.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/ui_tools/views.py
This introduces an optional argument, `--explore/-e`, to run the app in an explore mode where messages are not marked as read intentionally.
Tests amended and added.
Fixes #585.
=> Add an explore mode to run the app without marking messages as read

tests/helper/test_helper.py, tests/ui_tools/test_buttons.py, zulipterminal/helper.py, zulipterminal/ui_tools/buttons.py
The PR adds support for handling internal links - stream, topic and near narrow.
The commits introduce `MessageLinkButton` in `MsgInfoView` and then incrementally add support for different narrows.
I would greatly appreciate any feedback on the changes, the commit chronology and the structure in general.
Partially fixes #352 and #764.
=> Handle internal links

docs/FAQ.md
This is a slightly more detailed follow-up after #787, discussing how ZT handles marking messages read, since it varies slightly from the webapp.
This was motivated after reading threads of people asking about this in the webapp, and of course we handle it differently - so we should document this!
=> FAQ: Add entry discussing when messages are marked as read.

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This is an alternative to a commit from #700 - instead of allowing (leading) spaces in the text box, leading to "   x" being valid, they're just not accepted, by use of `valid_char()`.
=> Invalidate leading spaces (in panel boxes)

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This allows multiple aspects which improve the typeahead experience:
* editing of typeahead with stars (currently `@us` may generate `@**user**`, but backspacing to `@**u` doesn't autocomplete)
* specification of `@**` for autocompleting only users
* specification of `@*` for autocompleting only groups (fixing #732)
This doesn't resolve the same issue experienced in topic typeahead in the topic recipient box, namely that only full words can be autocompleted.
=> Add support for 'starred' typeaheads

tests/ui/test_utils.py, zulipterminal/ui_tools/utils.py
This causes a traceback for me when I do a specific search, since checking muted topic status assumes the stream is subscribed.
The test is updated but is rather implementation-specific.
I'd like to refactor the code further, so this is a bugfix which would benefit from being addressed better in future.
=> bugfix: Ensure subscription status checked before muting status.

Pipfile, docker/Dockerfile.alpine, docker/Dockerfile.buster, docker/README.md, requirements.txt, setup.py
The current docker files in docker/Dockerfile.* build images by pulling
our releases from pypi. This commit introduces the 2 docker files at
docker/dev.Dockerfile.* which build images by using the latest code from
master, merged upstream.
README updated to reflect the new change.
=> docker: Add dockerfile for building images from latest code (upstream).

tests/conftest.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py
The PR has been updated to use a factory fixture instead. This would help in compacting our tests and also correcting our keypress sizes (see asserts in the code).
Every `Use/Migrate ...` commit adds extra assert statements for sanity-check and every `Remove ...` commit removes those statements along with `size`. These are ordered alternatively, so we could either squash them in pair or let them be as-is.
The prior discussion for this can be found here: https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Compacting.20tests.
=> refactor: tests: Eliminate hard-coded size variables from keypress tests

tests/ui/test_ui_tools.py, tests/ui_tools/test_popups.py
We discussed this in the past in #**zulip-terminal>Splitting UI tests** - now seems a good time to make this change.
This moves all popup-related tests, resulting in ~400 lines moved, making the general test file change from ~2.8klines to ~2.4klines - and simplifying imports.
**I'm not sure we have particular open PRs which should be impacted by this, but please let me know if there are specific ones you know are impacted.**
=> Migrate popup tests out of general ui_tools file

.travis.yml, setup.py
The main enhancement is the support for testing/installation on py3.9.
However, this also fixes a few other issues:
* PyPy now indirectly appears to require a later openssl build, so dist is set to bionic
* Update the travis config generally to be more explicit and resolve the config warnings during travis builds
=> Add Python 3.9 to CI/installation (& other travis adjustments)

tests/model/test_model.py, zulipterminal/model.py
Previously these events contained single stream and user ids, but now instead contain lists of each to reduce the numbers of events required for cases where users join or leave large numbers of streams.
This is already merged into master as of https://github.com/zulip/zulip/commit/7ff3859136638defff01abafcaa8db51a2e2eb54, so pending zulip/zulip#16628, this should limit breakage for those using czo.
=> Adjust subscription op=peer_* events for ZFL35+

tests/conftest.py, tests/ui/test_ui_tools.py, zulipterminal/config/symbols.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This moves from having a single small bullet to a style similar to the
webapp, with circles of varying degrees of fullness:
* filled (active)
* bottom-filled (idle)
* empty (offline)
* small (inactive)
Tests updated.
NOTE: I'll move the unicode to symbols.py before this is merged.
=> Use varying symbols for user status.

tests/core/test_core.py, zulipterminal/core.py, zulipterminal/model.py
This extends an approach originally in a commit by @amanagr some time ago to use an urwid pipe to allow exceptions to be passed across threads. This is a more general form which I've had in a branch for some time.
While this doesn't yet take this approach as far as it could go, this has some rather important benefits already, most noticeably if an exception occurs during event handling:
* the event loop keeps running
* the exception is logged to a file
* a notice window is shown indicating an error occurred, where to report it and where the report is logged 
The limitations in this PR right now are:
* lack of explicit tests; this has been manually tested and appear to work fine
* perhaps configuring the exception output to use a standard logger from run.py?
=> Support inter-thread exception handling

Pipfile, requirements.txt, setup.py, tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This should partially or fully fix #776, but is pending on https://github.com/rr-/urwid_readline/pull/16 and assumes there will be a release of urwid-readline. For now my branch can be used to test this behavior; this allows 2 xfail-ing tests to be set to act normally.
=> Autocomplete with exact matches in stream & topic compose boxes

tests/model/test_model.py, zulipterminal/model.py
This is the trailing commit of #785 with extra refactoring and a bugfix to ensure topic list update is independent of message indexing.
Closes #785 
@kaustubh-nair I've not touched your original commit; how does this look?
=> 785 with refactors and extra bugfix

README.md
Following up on my comment in #859, this hopefully clarifies the keyboard-centric aspect, as well as starting to clarify the focus of the project and some limited caveats which could provide some scope to link to a document supporting #731 later.
=> README: Add About section (including feature status notes)

.github/workflows/lint-and-test.yml, README.md
@sumanthvrao This is a follow-up to the discussion we had in #831 - it doesn't make much difference to the runtime, but this now just runs codecov when running the tests under one version of python - 3.9 (we could pick some fixed element in the python version array instead if we could determine the appropriate syntax).
I also noticed that we can filter the default view to the master branch on the badge and get an improved UI using the `app.` website for Codecov (going back further than 6 months, for example).
@rht Thanks for pointing out the github action for codecov in the API repo PR :)
=> Codecov improvements

setup.cfg, tests/cli/test_run.py, tests/config/test_themes.py, tests/conftest.py, tests/helper/test_helper.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py, zulipterminal/cli/run.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This also will enable compatibility with black, if we move to that tool in the future.
=> tools: Use isort multi-line style '3' for smaller diffs.

tests/cli/test_run.py, zulipterminal/cli/run.py
This is the first part of #841 with some extra work and a few other commits first to help application of that refactor, and to extract DEFAULT_SETTINGS into a central place.
@Abhirup-99 Happy to take feedback :)
=> Refactor run.py with DEFAULT_SETTINGS & simple error exits

zulipterminal/model.py
This could do with a unit test, though it's just a refactor right now and the tests would potentially cover a large state space.
I'm thinking this could be useful in many ways right now already as an available method that could be used in various places.
@zee-bit Could this be useful for #824 if you constructed a fake message dict to pass in?
=> refactor:Extract function for message being in a narrow

zulipterminal/ui_tools/boxes.py
Setting the type of the input model in MessageBox initializer correctly should ensure that this is picked up in future by mypy.
@prah23 I noticed this issue when reviewing #877 and isolated it to being a separate issue.
One deeper optimization we could make is not to send the typing status if it's a self-message, but it seems to be OK right now.
=> bugfix: boxes: Ensure self-message recipient_ids are a list.

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
Autocomplete now splits on just `','` instead of `', '`.
The users would only have to use a `,` and continue with typing the next recipient and receive suggestions through autocomplete, without having to worry about adding a space.
=> Remove space to split recipients by ','.

tests/config/test_keys.py, tests/ui_tools/test_buttons.py, zulipterminal/cli/run.py, zulipterminal/config/keys.py, zulipterminal/config/themes.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/tables.py, zulipterminal/ui_tools/utils.py, zulipterminal/ui_tools/views.py
Ran `com2ann` in the project folder to auto re-write the files.
Fixes: #901
=> refactor: Move from type comments to inline type annotations.

docs/developer-file-overview.md, tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/server_url.py, zulipterminal/ui_tools/utils.py
This PR combines:
* extracting types that should match the Zulip API into a separate file, reducing coupling and making it clear they are not related to the implementation
* splitting the existing Event type from a large TypedDict which may not contain every element into multiple TypedDicts which must contain all elements
I was working on the latter last year, but the python3.6 changes make this much neater.
=> Extract api types & split Event

zulipterminal/api_types.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
Previously a draft was a Message, which is a much more complex data
structure received from the server with differently-named fields. The
draft system only requires the data which is subsequently sent via
the send_message API call, so a simpler API-specific set of data
structures are created and used for drafts named ~ Composition.
Other than typing, the new data structures allow space to define where
we wish to move to use newer API forms (ids vs strings) in future. An
extra 'stream_id' field is present in StreamComposition, not present in
the API, until we migrate to use IDs.
To emphasize the message/draft distinction and migration, variable names
are also updated to match.
=> refactor: Clarify draft types & naming

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
Feedback on whether this is truly dead would be appreciated; the commit history is not so helpful for this.
This tidying was derived from #903, which likely will benefit from rebasing on top of something like this, if not this.
=> Remove dead code in load_old_messages & simplify tests.

zulipterminal/api_types.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
This removes the non-API stream_id field from StreamComposition, allowing it to be used more widely.
=> Clarify StreamComposition and apply to message-sending 

tools/convert-unicode-emoji-data
* Use `pathlib` rather than `os`
* Use f-strings and double quotes where generated data is unchanged
* Use strings over many lines rather than repeated function calls
* Cleanly handle the server unicode emoji not yet having been fetched
* Use the script name rather than hard-coded text
=> tools: Modernize convert-unicode-emoji-data.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
An earlier commit 2b8a3050 brought about consistency in using `x` and `c`.
This commit aims to build on top of that by prefilling the steam name in
`stream_box_view` when the user presses `c` from stream/topic narrow.
Minor test amendment.
=> boxes: Prefill stream name when user presses `c` in stream/topic narrow.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This commit fixes a bug which originated in commit a9306da0 due to
stream id being passed into `narrow_to_topic` function in place of
stream name.
Tests amended.
Fixes #957.
=> bugfix: views: Restore functionality of keypress `n`.

README.md, docs/FAQ.md
As discussed in #**zulip-terminal>Small terminal sizes**.
=> README/FAQ: Add intent & notes to support 80x24 size terminals upwards.

setup.py, tests/model/test_model.py, tests/ui_tools/test_boxes.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py
This PR restricts input beyond certain max-limit for compose
box, as specified by the corresponding parameters in initial_data's
realm object. ZT didn't had this restriction earlier which resulted
in certain long topic names/messages getting cropped from the end
without the user noticing, until the message was sent.
These parameters were recently added in ZFL 53 in [`4a3ad0d`](https://github.com/zulip/zulip/commit/4a3ad0da06b3e8db511e9690b31507b565f7f2fc), so we allow for
backporting by defining hard-coded values for these parameters.
The content restriction of compose boxes was made possible only
after urwid-readline merged a patch in v0.13, which added support
for specifying a `max_char` argument to their `ReadlineEdit` widget.
Related patch: …
=> bugfix: Restrict content-length for compose box.

docs/developer-file-overview.md, zulipterminal/config/ui_mappings.py, zulipterminal/helper.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This moves and renames (capitalized) edit_mode_captions into the new
config/ui_mappings.py, representing relationships between state and how
it is presented.
Documentation added for the file content.
=> ui_mappings: New file for edit_mode_captions

tests/core/test_core.py, zulipterminal/core.py
This commit is a step towards solving #1005 especially the first
2 points. This changes the fixed scaling fraction of 3/4 to one that
is linear in the range 80 - 100 column width:
* The scaling fraction increases from 3/4 to 1 (full-width) as the
available size increases from 80 to 100. This increases the range of
sizes for which the popup is rendered properly.
* For width's smaller than 80 it defaults to full width.
* For width's greater than 100 it defaults to 3/4.
The values 80 and 100 are given by:
* MIN_SUPPORTED_POPUP_WIDTH = 80
* MAX_LINEAR_SCALING_WIDTH = 100
The popup height has a fixed scaling factor of 2/3.
Tests added
80 < Width < 100
Width = 80
Width > 100 (Full screen)
=> popup: core: Use linear scaling for small terminal sizes.

tests/conftest.py, tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
Continues work on #825. 
Processed `initial_data['realm_emoji]` and set `custom_emoji_data` according to the schema given by `NamedEmojiData`.
Similar processing for `realm_emoji_update` before updating `active_emoji_data` in `_handle_update_emoji_event`.
Also, the deactivated realm emojis are removed from `active_emoji_data`.
=> model: Fetch realm emoji using events

docker/Dockerfile.alpine
`cryptography` now requires Rust toolchain on Alpine Linux, xref https://cryptography.io/en/latest/installation/#alpine
=> cryptography requires Rust toolchain on Alpine Linux.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
Currently, a configuration of 0 for `realm_message_content_edit_limit_seconds`
is treated as a complete restriction against message body editing, while
the configuration actually signifies no limit in message body editing.
This PR adds a commit that fixes the bug that doesn't let the users
edit the message body when the configuration sent by the server is 0
for a realm. 
Fixes #1034.
=> bugfix: boxes: Allow message body editing when limit doesn't exist.

README.md, docs/FAQ.md, docs/getting-started.md
While reading the README, I stumbled upon a typo and decided to run the README through [Grammarly](https://www.grammarly.com/). We had two. I have fixed them in the commit.
=> README/docs: Fix minor typographical errors to improve readability

README.md
This is for the v0 solution at #**zulip-terminal>Update alerts (README)**, namely to document where updates are announced.
I've not seen an obvious way to subscribe to GH or PyPI updates explicitly, so have left it at text for now.
Feedback welcome.
(v1: Add network call to check API updates & warn if out of date, plus note that we call home)
(v2: Add "advanced" config feature to disable calling home?)
=> README: Add Install subsection for keeping up to date.

tests/ui/test_ui.py, zulipterminal/ui.py
This commit fixes a bug that caused the focus to not move to the content
area if the draft was opened from the side-panels. This is minor bugfix
that should set the focus to the message_column before setting it to
the footer(i.e. content_area).
=> bugfix: ui: Focus on content_area when draft is opened from side-panels.

docs/hotkeys.md, tests/core/test_core.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/ui_tools/views.py
Thanks to @punchagan and @preetmishra for their major initial work in #397 and #698 respectively. :+1:
This PR extracts some initial commits from both PR's and cleans and refactors them. It also adds support for opening external links in the browser from the `MessageLinkButton`. All the reviews on the previous PR's have also been addressed, facilitating further reviews.
Fixes last point of #452.
=> Add support for opening message and external links in browser.

tests/conftest.py, tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This PR adds a commit that append `user_id`s to the users' names in the autocomplete typeahead for user mentions. This helps in distinguishing between users having the same name, similar to the pm recipients autocomplete.
Tests updated.
Fixes #151.
=> boxes: Use `user_id`s in autocomplete for user mentions.

tests/helper/test_helper.py, zulipterminal/helper.py
**PR Structure:**
- **refactor: tests: Change req parameter to use a list of recipient emails.**
This commit refactors the test cases of the `req` parameter in
`test_notify_if_message_sent_outside_narrow` from a string of ', '
separated emails to a list of emails, consistent with the current type
of the `to` attribute of PrivateComposition.
Tests updated.
- **bugfix: helper: Use ', ' as separator to construct narrow to verify.**
This commit fixes a bug that previously caused a "Message sent outside
current narrow." message in the footer in group pms (huddles) even when
on the right narrow. This happened because of the wrong separator being
used, ','. This has been changed to the relevant separator - ', '.
Test added.
**Testing and linting:**
I've ran tests locally on each commit. I've …
=> bugfix: Construct narrow appropriately before verifying and triggering footer notifications.

tests/conftest.py
This is a prep commit for #967, that simplifies the message template generation logic in `conftest`. Using factory fixtures to generate templates for all messages(stream/PM/group), rather than separately defining for each type allows for code reusability and prevents duplication.
=> refactor: Simplify msg template generation in conftest using factory fixtures.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This PR corrects what the code for `focus_index_before_search` was intended to do. See #975
The focus index was still being updated even in the search results.
This is fixed by moving `get_focus` into the SEARCH_STREAM/TOPIC
conditional.
Fixes #975
| Before Commit: | After Commit: |
| :-------------------: | :-----------------: |
| <img src="https://user-images.githubusercontent.com/64144419/113336052-6f0ac200-9343-11eb-97df-ee06a8739082.gif" alt="wrong-focus" height="300"/> | <img src="https://user-images.githubusercontent.com/64144419/113336589-47682980-9344-11eb-8d78-a03df5a7e743.gif" alt="right-focus" height=300/> |
=> view: Fix focus index before and after Panel Search.

tests/conftest.py, tests/core/test_core.py, zulipterminal/core.py
This bugfix fixes selecting messages if a contextual msg-id (anchor) is provided to the `_narrow_to()` function for some edge cases. Earlier, if the user was within the same narrow then narrowing to a quoted message from `MsgLinkButton` did not select that message. Also, sometimes pressing `a` on a particular message did not focus on it when narrowed to the `all_messages` narrow.
Tests added.
Fixes #954.
=> bugfix: core: Fix cases where message was not focused on narrowing with anchor.

docs/FAQ.md
This PR adds a section `How do I use autocompletes in ZT?`, which lists and explains the working of currently supported autocompletes in ZT, grouped by different compose boxes
- Message body autocompletes
- Other (Stream/Topic/PM recipients) autocomplete options
**NOTE:** Currently I'm not sure if the first bullet title is user-friendly, and so would appreciate feedback/suggestions for the same :)
=> docs: Add autocomplete info section in FAQ.

README.md
Link to Commit Style (GitLint) sections updated.
=> README: Split out Commit Style notes into an expanded section.

tests/ui_tools/test_boxes.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py
This PR adds a commit that refactors the `get_invalid_recipients_emails()` method
of the model to `check_recipient_validity()` which checks if the
recipient's name and email match.
This commit follows this strategy:
* Ensures that the email and the name are of the same user.
* Removes extra text after the email.
The recipients' information is also tidied for all the valid recipients,
by formatting the information to fit the `name <email>` format.
=> Enhance validation and check for bad/no recipients in PMs

tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
Recent work in resolved/unresolved topics has caused a change in the server (not yet in a release), where it more strictly enforces that if a topic is provided but unchanged in stream message editing/updating, then the propagate mode must be set to change_one - otherwise the edit does not proceed.
This PR works around this and has scope to be expanded towards resolving part or all of #1014.
The need for this was discussed in #**design>closing/solving a topic (#11154)**.
I've not added tests for this change in behavior (yet, at least) - we don't seem to have tests for the existing behavior.
=> bugfix: Fix topic editing if topic unchanged

tests/ui/test_ui_tools.py, zulipterminal/config/ui_mappings.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
**What does this PR do?!**
- Adds sender's presence status marker in a message content header
- Centralize the state icons in `ui_mappings.py` (*refactor*)
- Add state marker as a prefix to sender names in the message header.
- Add helper in `MessageBox` to update author field if present.
- Add a method to render presence markers in messages regularly.
**Screenshots/GIFs**
Fixes #896.
=> Show sender's presence status in message content header

tests/cli/test_run.py, zulipterminal/cli/run.py
This commit changes the warning text shown at startup if the theme
is incomplete. If there aren't any complete themes to suggest
the warning displays "(all themes are incomplete)".
Tests updated.
=> Improve incomplete theme warning text when all are incomplete.

tests/cli/test_run.py, tests/core/test_core.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, tests/ui/test_utils.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_buttons.py, tests/ui_tools/test_popups.py
Currently, in pytests, several statements use hard-coded module path strings for patching purposes.
The intent of this PR is to refactor such statements and as a result, reduce code duplication.
=> refactor: tests: Add path prefixes for patching class methods

tests/cli/test_run.py
**Commit structure:**
- **tests: run: Use the `tmp_path` fixture instead of `tmpdir`.**
The `tmpdir` fixture under `pytest` is a `py.path.local` object,
belonging to the `py` library, which is currently under maintenance
mode, mentioned in the note here:
https://py.readthedocs.io/en/latest/path.html#py-path.
This commit migrates from `tmpdir` to using the `tmp_path` fixture
instead, which is a `pathlib.Path` object.
Reference: https://docs.pytest.org/en/6.2.x/tmpdir.html
**Testing and linting:**
I've ran tests locally on each commit. I've also ran `black` checks and then the more extensive `./tools/lint-all`.
=> tests: run: Use the `tmp_path` fixture instead of `tmpdir`.

.github/pull_request_template.md
Adds a pull request template, like I'm using here :)
Take a look at the raw and rendered versions to get a full idea of the contributor experience.
**Tested?** 
**Notes/Doubts/Concerns/Questions** 
This is more detailed than others I've seen, eg. https://raw.githubusercontent.com/zulip/zulip/master/.github/pull_request_template.md
Do we need the top title? Or feature/bug boxes? (except for suggesting what it may fix?)
Do the testing boxes help? Do they just take up space?
=> github: Add pull request template.

docs/hotkeys.md, tests/conftest.py, tests/model/test_model.py, tests/ui_tools/test_buttons.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/config/themes.py, zulipterminal/config/ui_mappings.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/themes/gruvbox.py, zulipterminal/themes/zt_blue.py, zulipterminal/themes/zt_dark.py, zulipterminal/themes/zt_light.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
**What does this PR do?!**
- Adds a basic interpolable user info view from web app.
- Custom fields omitted for now.
- Press `i` in the users list to see user info.
1. Create UI <=> API mappings for a realm user.
2. Adds a method to return tidied user info, so that it becomes displayable.
3. Support backward compatibility of API user response.
4. Adds hotkey `i` to trigger the popup.
5. Structures the user info popup to be shown.
6. Adds UI elements for toggling the popup.
7. Adds keypress events to trigger the popup.
Fixes #511
**Screenshots/GIF**
=> Feature: Add user info view

tests/cli/test_run.py, tools/run-mypy
Adds type annotations to the `test_run.py` file. Includes this file under the `run-mypy` tool to type-check.
**Tested?** 
- **refactor: tests: run: Add type annotations.**
This commit adds paramter and return type annotations or hints to the
`test_run.py` file, that contains tests for it's counterpart `run.py`
from  the `zulipterminal` module, to make mypy checks consistent and
improve code readability.
- **tools: Include test_run.py under files to be type-checked with mypy.**
This commit adds a new "tests" key to the `repo_python_files` dict to
let mypy know which files to type check. A new list,
`type_consistent_testfiles` is also added, to hold the list of test
files that have been type-annotated incrementally till all the test
files are …
=> tests: run: Add type annotations.

tests/model/test_model.py, tests/ui_tools/test_popups.py, zulipterminal/config/themes.py, zulipterminal/model.py, zulipterminal/themes/gruvbox.py, zulipterminal/themes/zt_blue.py, zulipterminal/themes/zt_dark.py, zulipterminal/themes/zt_light.py, zulipterminal/ui_tools/views.py
- Added Visual desktop notification checkbox in StreamInfo.
Gradually Fixes #887.
=> model/views: Add notification checkboxes in Stream Info popup.

tests/conftest.py, tests/core/test_core.py, tools/run-mypy
Adds type annotations to the test_core.py file. I've also added a few refactor/bugfix commits. 
**Tested?** 
- **bugfix: tests: core: Replace incorrect return type annotation.**
- **bugfix: tests: core: Assign ThemeSpec instance to controller theme.**
- **refactor: tests: core: Use mocker.patch for model.is_muted_topic.**
- **bugfix: tests: core: Assign a set to model's muted_streams.**
- **refactor: tests: core: Use mocker.patch for `report_*` methods.**
- **tests: conftest: Add an index_search_messages fixture.**
- **refactor: tests: core: Use index_search_messages in search tests.**
- **refactor: tests: core: Add type annotations.**
- Waiting on #1076 to extend the changes made to the `run-mypy` tool.
=> tests: core: Add type annotations.

tests/core/test_core.py, tests/ui_tools/test_buttons.py, zulipterminal/core.py, zulipterminal/ui_tools/buttons.py
Prior to this PR, the `stream_muting_confirmation_popup` required
a `StreamButton` instance as a parameter to mute/unmute it and show
it to the user to request for confirmation. This PR refactors
the parameters to require the `stream_name` and `stream_id` instead
to abstract the StreamButton from this method.
**Tested?** 
- refactor: buttons/core: Avoid using StreamButton as a popup parameter.
Prior to this commit, the `stream_muting_confirmation_popup` required
a `StreamButton` instance as a parameter to mute/unmute it and show
it to the user to request for confirmation. This commit refactors
the parameters to require the `stream_name` and `stream_id` instead
to abstract the StreamButton from this method.
Tests updated.
=> refactor: buttons/core: Avoid using StreamButton as a popup parameter.

tests/emoji_data/test_emoji_data.py, tools/run-mypy
Adds type annotations to the `test_emoji_data.py` file. Also updates the `run-mypy` tool to run mypy on it.
**Tested?** 
- **refactor: tests: emoji_data: Add type annotations.**
- **tools: Include test_emoji_data.py to be checked by mypy.**
=> tests: emoji_data: Add type annotations.

tests/conftest.py, tests/ui/test_ui_tools.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This PR aims to replace all hard-coded keys in keypress to use their corresponding commands, to make them future-proof. 
Commit flow:
- The first commit is borrowed from @preetmishra's #539, which parametrizes mouse_event calls and adds mouse_event test for `TopicsView`.
- The second commit migrates all instances of hard-coded keys in mouse_events to use `primary_key_for_commands`.
- The third commit replaces all other instances of hard-coded keys in keypress to use their corresponding commands so that they are future-proof.
- The fourth commit is a bugfix that makes `r` for replying to message independent of `ENTER` key.
Our codebase would have no instances of hard-coded keys now. Can be checked using: `git grep keypress\(size`
Fixes #469 and #533.
=> refactor/bugfix: Migrate keypress to using commands instead of hardcoded keys.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
* Adds MIDDLE_COLUMN_MOUSE_SCROLL_LINES and SIDE_PANELS_MOUSE_SCROLL_LINES
global variables in views to store the scroll values for both columns.
* Assigns mouse scroll values of 1 and 5 to Middle column and Side panels
respectively.
* Uses these values in mouse_events to skip defined number of lines on
each scroll, making scroll lines for all side-panels consistent with each
other.
**Tested?** 
Can we simplify the names of the global variables?
=> refactor: views: Make mouse scroll-speed in side-panels consistent.

tests/helper/test_helper.py, tools/run-mypy
Adds type annotations to `test_helper.py`. I've also added a prior bugfix commit changing `muted_streams`' data structure from List to Set and a final follow up commit to include `test_helper.py` in the list of files being checked by `run-mypy`.
**Tested?** 
- bugfix: tests: helper: Use Sets as params for muted_streams.
This commits changes the previous incorrect configuration of `Lists`
to the `muted_streams` parameter in `test_classify_unread_counts`
which is assigned model's muted_streams, to `Set`s instead, which is
the appropriate data structure.
- refactor: tests: helper: Add type annotations.
This commit adds parameter and return type annotations or hints
to the `test_helper.py` file, that contains tests for its counterpart
`helper.py` …
=> tests: helper: Add type annotations. 

zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py
This commit fixes 2 bugs related to displaying selection_hint on mouse_drag
events. This migrates the mouse_event from MessageBox to the entire View
so that the selection_hint is displayed even when the user tries to perform
mouse_drag events outside of MessageBox i.e. anywhere in View.
This also fixes selection_hint getting stuck in the footer if the mouse is
dragged in the MessageView but released outside of it.
Thanks to @Rohitth007 for reporting this bug in [#zulip terminal>Drag-to-select-text](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Drag-to-select-text)
**Tested?**
=> bugfix: boxes/ui: Display mouse selection_hint for entire `View`.

.github/workflows/lint-and-test.yml, README.md, setup.py, tools/generate_hotkeys.py, tools/gitlint-extra-rules.py, tools/lint-all, tools/lister.py
With tools/ and setup.py included in black linting, all python files will then be checked by black :tada:
These were originally excluded for simplicity, but to remove certain linting rules it is useful to ensure black is applied to all python files, such as for line length ie. removing flake8 rule E501 in #1084 
This is a partial fix towards #1047 
**Tested?** 
As per the original main black transition:
* adapt a few files for things black has issues with or can be handled manually simply
* apply black without quote adjustment (just structure; needs more review)
* apply black with quote adjustment (generally no need to review as black just does it fine)
* enforce black in tools
I'd like to merge this before #1084, since that …
=> Apply black to tools/ and setup.py

tests/server_url/test_server_url.py, tools/run-mypy
Adds type annotations to `test_server_url.py` and includes it under files to be checked by mypy in the `run-mypy` tool.
**Tested?** 
- refactor: tests: server_url: Add type annotations.
This commit adds parameter and return type annotations or hints
to the `test_server_url.py` file, that contains tests for its
counterpart `server_url.py` from  the `zulipterminal` module, to
make mypy checks consistent and improve code readability.
- tools: Include test_server_url.py to be checked by mypy.
This commit adds `test_server_url.py` to the
`type_consistent_testfiles` list to check for type consistency
with mypy.
=> tests: server_url: Add type annotations.

tests/ui_tools/test_popups.py, zulipterminal/ui_tools/views.py
This bug was introduced by the first commit of #874 which was just cherry-picked, and hidden since the button
used in the EditModeView tests did not have any state to trigger the code in question.
Tests extended.
**Tested?**
=> bugfix: views: Ensure EditModeView works with new frame-based popup.

tests/ui/test_ui.py, tools/run-mypy
Adds type annotations to `test_ui.py` and includes it under files to be checked by mypy in the run-mypy tool. Also added a couple of prior commits to use appropriate patches.
**Tested?** 
- refactor: ui: Patch *_box_views in OPEN_DRAFT tests.
This commit assigns patches `stream_box_view` and `private_box_view`
using `mocker.patch.object` to maintain type consistency since their
mocked nature's assert methods are being called.
- refactor: ui: Use patch for non-existent attributes instead of Mock.
This commit uses `mocker.patch` with the `create` parameter set as
True for attributes of the `View` fixture instance that don't exist
without their corresponding generation methods being called. `View`'s
`middle_column` is generated by the …
=> tests: ui: Add type annotations. 

.github/workflows/lint-and-test.yml, setup.cfg, tools/convert-unicode-emoji-data, tools/fetch-unicode-emoji-data, tools/font-styles-test, tools/gitlint-extra-rules.py, tools/lint-all, tools/lister.py, tools/python_tools.py, tools/run-mypy
This is a follow-up to #1087, which did not fully achieve its aim since python scripts without a `.py` ending were not identified.
Other scripts are now updated to be covered, with an additional script providing a list of tools in python, given certain known exclusions. This script is used as a module in `tools/lint-all`, and separately in CI to explicitly include those files.
A broader approach is likely possible with zulint or using lister.py in future, but having these files covered and tested, and not accidentally losing compliance is the intent here.
**Tested?**
=> Blacken/lint rest of tools/

docs/hotkeys.md, tests/model/test_model.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
**What does the PR do?!** :
- Allows scrolling for large single messages 
**Note: currently true for every message**
- Provides raw and rendered message view to users.
**Commit flow:**
- refactor: views: Use urwid.Frame for PopUpView.
- boxes: Add members to MessageBox to fetch header, content, footer.
- hotkeys/keys: Add f hotkey for full rendered message popup.
- views: Structure FullRenderedMsgView class.
- core: Add controller helper to show full rendered message on toggle.
- views: Add keypress events for showing/hiding full rendered message.
- model: Add support for fetching a raw message.
- refactor: boxes: Use new model method to fetch a raw message.
- hotkeys/keys: Add r hotkey for full raw message popup view.
- views: Structure FullRawMsgView class.
- core: Add controller helper …
=> Scrollable large single msg view

tests/ui_tools/test_buttons.py, zulipterminal/ui_tools/buttons.py
This fixes a minor regression in selection of buttons with colored text after the refactoring to use more internal button features.
Without this fix then muted streambuttons and userbuttons don't appear as strongly selected when the cursor is on them, as the main text does not highlight.
**Tested?** 
@Rohitth007 I'd welcome your feedback here - this seems like an appropriate minimal solution?
=> buttons: Ensure muted button text color is adjusted when selected.

tests/config/test_color.py, tests/config/test_keys.py, tests/config/test_themes.py, tools/run-mypy
Adds type annotations to the `test_keys.py`, `test_themes.py` and `test_color.py` files. Adds these files to the list in `run-mypy`.
**Tested?** 
- bugfix: tests: keys: Use lists for keys of key bindings. 
This commits replaces the data structure used for mentioning the keys
of the various key bindings under `test_commands_for_random_tips` from
`set` to `list` which is the right structure.
- refactor: tests: keys: Add type annotations.
This commit adds parameter and return type annotations or hints
to the `test_keys.py` file, that contains tests for its counterpart
`keys.py` from  the `zulipterminal` module, to make mypy checks
consistent and improve code readability.
- tools: Include test_keys.py to be checked by mypy. 
This commit adds …
=> tests: config: Add type annotations.

tests/helper/test_helper.py, tests/platform_code/test_platform_code.py, tools/run-mypy, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/platform_code.py, zulipterminal/ui.py
This PR improves our platform handling by defining an isolated module `config/platform_detection.py` that contains the platform detection code and uses a single variable `PLATFORM` to hold the name of the platform that the current ZT instance is loaded on. This fixes a bug in WSL where multiple platforms were detected. Related discussion in: [#zulip-terminal>Platform handling (#T791) and WSL issues](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Platform.20handling.20.28.23T791.29.20.20and.20WSL.20issues)
Fixes #791.
=> Platform handling improvements and WSL bugfix.

tests/conftest.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_buttons.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This PR fixes the bug that made incoming new topics rendered badly when the topic list was open due to incorrect parameters being passed to `TopicButton`. This PR also migrates `TopicButton` to accept only named parameters so that there's no scope of bug and connascence between parts of the program is reduced.
The discussion regarding this bug can be found in [#zulip-terminal>New-topic topic-list bug](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/New-topic.20topic-list.20bug/)
=> Fix bad rendering of new topics when topics list was open.

docs/hotkeys.md, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/config/markdown_examples.py, zulipterminal/core.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
**What does this PR do?!**
- Adds a message formatting help menu.
- Creates a new config file `markdown.py` for markdown-related material.
- Fixes #623.
1. Add hotkey `meta m ` to show markdown popup.
2. Create a new file `markdown_examples.py` containing markdown help data.
3. refactor: Amend the type annotation for PopUpView contents.
4. Structure UI in MarkdownHeloView class.
5. Add UI elements to markdown help view on toggling.
6. Add support for accessing the popup from compose area.
**Doubts/Concerns**
- The Popup name, i.e., `MarkdownHelpView` could be replaced with one having `message formatting` instead?.
- The markdown help data might be migrated to `ui_mappings`
**Screenshot(s)/GIF(s)**
=> Add message formatting tips help menu

tests/ui_tools/test_buttons.py, tools/run-mypy
Adds type annotations to test_buttons.py and adds the file to the list in run-mypy. Also has a prior refactor commit to assign `mocker.patch`s to variables.
**Tested?** 
- refactor: tests: buttons: Assign method mocker.patchs to variables.
This commit assigns fixture method attribute `mocker.patch`s to
variables, so that the corresponding asserts can be called on the
mocked nature, as was the original intention.
- refactor: tests: buttons: Add type annotations.
This commit adds parameter and return type annotations or hints to the
`test_buttons.py` file, that contains tests for it's counterpart
`buttons.py` from  the `zulipterminal` module, to make mypy checks
consistent and improve code readability.
- tools: Include test_buttons.py to be …
=> refactor: tests: buttons: Add type annotations.

tests/config/test_themes.py, tests/ui_tools/test_boxes.py, zulipterminal/config/regexes.py, zulipterminal/helper.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py
The PR does the following tasks:
- Fixes a bug re space-separated typeaheads (commit 1),
- Extracts all regexes to a new file `regexes.py` (commit 2-5)
- Adds support for stream+topic autocompletes. (commit 6-9).
Ticks a check box in #448.
=> Add support for stream + topic autocomplete

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
**PR structure:**
- **boxes: Use an indicator attribute to specify current compose box status.**
This commit introduces an attribute, `compose_box_status` to the WriteBox
class, to indicate the current compose status of the WriteBox, which can
be one of "open_with_private", "open_with_stream" or "closed". Such an
indicator would be a structured way to check for compose status before
performing status specific tasks.
- **boxes: Create a helper method to set WriteBox attributes to defaults.**
This commit adds a helper method to the WriteBox class to reset all
the WriteBox attributes to their defaults after usage by the
`stream_box_view` or `private_box_view`. This helps to ensure that
the state of the attributes do not persist beyond their function.
- **boxes: Configure `*_box_views` to set …
=> boxes: Use indicator attribute to hold compose box status.

tests/ui/test_ui.py, zulipterminal/ui.py
This commit makes the side panels to overlay the body which avoids
squashing and stretching of the message view which improves UX in
autohide mode.
**Tested?** 
Built on PR #1097 
Waiting on PR #1097
Blocks PR #1074 
=> Overlay side-panel in autohide mode.

tests/ui/test_utils.py, tools/run-mypy
Adds type annotations to `test_utils.py` and adds the file to the list in `run-mypy`.
**Tested?** 
- refactor: tests: utils: Add type annotations. 
This commit adds parameter and return type annotations or hints to the
`test_utils.py` file, that contains tests for it's counterpart
`utils.py` from  the `zulipterminal` module, to make mypy checks
consistent and improve code readability.
- tools: Include test_utils.py to be checked by mypy. 
This commit adds `test_utils.py` to the `type_consistent_testfiles`
list to check for type consistency with mypy.
=> tests: utils: Add type annotations.

zulipterminal/themes/gruvbox.py
To make it consistent with zt_dark. We could deviate and use green instead. But the current Zulip logo is blue, so it's good to have more blue in the screen.
**Tested?** 
=> gruvbox: Change background of selected to dark blue.

tests/conftest.py, tests/ui_tools/test_popups.py
This PR defines the `general_stream` and `secret_stream` dictionaries in conftest to pytest fixtures, allowing us to re-use them in tests that need stream data. The defined fixtures are currently used in tests for StreamInfo popup.
**Tested?** 
- refactor: conftest: Define general_stream and secret_stream as fixtures.
- conftest: Add rendered_description field to stream fixtures.
- tests: popups: Use stream fixture instead of defining custom streams.
- Blocks #880
=> Define and use Stream data fixture from conftest

tests/conftest.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui.py, tests/ui_tools/test_boxes.py, zulipterminal/api_types.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py
There are 4 commits to this PR:
- The first commit refactors `update_recipient_emails()` to `update_recipients()`, also updating the recipients' `user_id`s now, which is a preparatory step for the third commit. A test has also been added for this method.
- The second commit adds a test fixture for `user_id_email_dict` as a prep commit for the third commit.
- The third commit migrates from using delivery emails as message destinations to using `user_id`s instead. Tests updated.
- The fourth commit deprecates the `emails` parameter from `private_box_view()`. Tests updated.
The abstraction between the narrow model and the Composition API type is maintained by modifying the corresponding connections to the narrow model such that the delivery emails are still in use in the narrow model …
=> Use `user_id`s as message destinations

tests/conftest.py, tests/model/test_model.py, tools/run-mypy, zulipterminal/api_types.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
Adds type annotations to `conftest.py` and some relevant prior refactors. Also includes `conftest.py` under the list in `run-mypy`.
**Tested?** 
- refactor: tests: conftest: Return a Message from template factory. 
This commit changes the returned object of the `msg_template_factory`
from a `Dict` to a `Message` instance, which is the appropriate type
for a message template.
- refactor: tests: conftest: Return Index instance from empty_index.
This commit returns an Index instance for the `empty_index` fixture
which previously returned a deepcopy of a Dict, as Index is the
`empty_index`'s appropriate type.
- refactor: test: conftest: Return Index instances for index_* fixtures. 
This commit returns Index instances instead of `dict`s from all the …
=> tests: conftest: Add type annotations.

tests/conftest.py, tests/model/test_model.py, tests/ui_tools/test_popups.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
=> Feature: Improve Stream Info Popup

tests/config/test_keys.py, tests/conftest.py, tests/ui/test_ui.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/ui.py, zulipterminal/ui_tools/views.py
This PR modifies urwid's `CommandMap` class object `command_map`
to map alternate navigational keys to standard urwid navigational
aliases. This is used in `ui.py` and `PopupView`.
Users can also now add custom nav-keys by adding it to KEY_BINDINGS.
**Tested?**
=> Use urwid's CommandMap to manage navigational keys.

docs/hotkeys.md, tests/ui_tools/test_boxes.py, tests/ui_tools/test_buttons.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This PR packs a critical feature, that supports adding general reactions to messages. Few highlights of this feature:
- A new `EmojiPicker` popup that activates from <kbd>:</kbd> hotkey.
- Search for any emoji in the list through <kbd>p</kbd> hotkey.
- A reaction count beside emoji's that users have reacted with.
- Emoji list sorted in decreasing order of reaction count, and ascending order of emoji names(if reaction count is same).
- A `CHECK_MARK` that indicates emoji's that the current user has reacted with.
- Mouse support allows toggling reactions and scrolling through mouse events.
**Working:**
Thanks to @kaustubh-nair for his initial work in #707. I was able to pull some of his changes here, which simplified my work.
=> feature: Add Reactions to messages.

tests/ui_tools/test_boxes.py, tools/run-mypy
Adds type annotations to `test_boxes.py` and adds the file to the list in `run-mypy`. Also has a prior refactor commit to remove unnecessary `mocker` parameters.
**Tested?** 
- refactor: tests: boxes: Remove mocker as parameter where unnecessary.
This commit removes the `mocker` fixture as a parameter from tests
where it isn't used.
- refactor: tests: boxes: Add type annotations. 
This commit adds parameter and return type annotations or hints to the
`test_boxes.py` file, that contains tests for it's counterpart
`boxes.py` from  the `zulipterminal` module, to make mypy checks
consistent and improve code readability.
- tools: Include test_boxes.py to be checked by mypy.
This commit adds `test_boxes.py` to the `type_consistent_testfiles`
list to …
=> tests: boxes: Add type annotations.

README.md, tests/core/test_core.py, zulipterminal/cli/run.py, zulipterminal/core.py
This mainly improves print debugging:
* just use `print("something")` instead of `print("something", flush=True)` (README updated)
* only open the `debug.log` file that `print` is redirected to, if `-d` or `--debug` is enabled (README updated)
There is also an intermediate refactor commit to require Controller to have named arguments.
Fixes #1066 (via the second part)
**Tested?**
=> Improve print-debugging (no `flush=True` required; require `-d`/`--debug`)

tests/ui_tools/test_popups.py, tools/run-mypy
Adds type annotations to `test_popups.py` and adds the file to the list in `run-mypy`. Also has a few related prior refactors to ensure type consistency.
**Tested?** 
- refactor: tests: popups: Remove unnecessary parameters. 
This commit removes the passing of parameters in test definitions
for parameters that are unused within the body of the test.
- refactor: tests: popups: Use Message instances to pass into views. 
This commit refactors the multiple `dict` assignments to View classes'
message attribute to Message instances instead to maintain type
consistency.
- refactor: tests: popups: Assign mocked keypress to a variable.
This commit assigns the mocked keypress method of the
emoji_picker_view within `test_mouse_event` of the …
=> tests: popups: Add type annotations.

.github/workflows/lint-and-test.yml, setup.py
This is essentially an upgrade to mypy 0.910.
However, from ~0.901, type annotations for libraries not in the standard library are expected to be pulled in externally. For this reason a separate extra is added to `setup.py` for use by CI when running mypy (first commit) and to group the dependencies together in the second commit when mypy is upgraded.
NOTE: I've provisionally used a `[dev]` in the commit area to indicate this is a dev-only change, which we can discuss.
**Tested?**
=> Isolate typing testing dependencies and upgrade to mypy 0.910

.github/workflows/lint-and-test.yml
We recently added CI support for a release-candidate version of CPython 3.10 - this is now released and available in Github Actions, so can be updated and should track later releases too.
PyPy support has been present for some time, but different python versions appeared to be challenging in the past - this seems more straightforward now, so we have separate tests under 3.6, 3.7 and 3.8.
(Note that more generally 3.6 will be end-of-life soon, so this will make updating specific python versions more explicit when we remove support too)
**Tested?** 
CI has been updated.
=> CI: Update to CPython 3.10 release and add specific PyPy versions (3.6, 3.7, 3.8)

makefile
Adds "$(PYTHON) -m pip install wheel" to the makefile, so as to install wheel if it isn't on the host system
(https://chat.zulip.org/#narrow/stream/2-general)
- [x ] Manually
See https://github.com/zulip/zulip-terminal#commit-style
=> Add "$(PYTHON) -m pip install wheel" to makefile

setup.py, tests/config/test_themes.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py
This PR updates the version of Black in venv when it is activated using the source zt_venv/bin/activate command
It incorporates the changes added in the new version of Black (22.1.0) in the venv (black module) and hence saves from unexpected formatting errors in the Lint test.
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Updating.20requirements.20for.20Black
**Tested** 
Will have to run make/pip install -e .[dev] to incorporate the changes.
=> Updating version of Black in venv

zulipterminal/themes/THEME_CONTRIBUTING.md
Updates #1144 
**Tested?** 
First Commit: Refactor: config/themes: Extract gruvbox colors into common file. [Modifies THEME_CONTRIBUTING.md as well]
Second Commit:  config/themes: Add gruvbox_light theme with extra gruvbox colors.
Updates PR #1144 
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/.E2.9C.94.20Gruvbox.20light.20.23T1144.20.28Issue.20.23T1133.29
The screenshots of both gruvbox themes (for different color depths) are as follows-
Gruvbox light theme
1) Color depth =16
[image.png](https://chat.zulip.org/user_uploads/2/45/4VnXZ1HEtlkTs-zrIGuTV-ht/image.png)[](https://chat.zulip.org/user_uploads/2/45/4VnXZ1HEtlkTs-zrIGuTV-ht/image.png)
2) Color depth =256 …
=> Clarify theme contributing doc after new theme gruvbox light

zulipterminal/themes/THEME_CONTRIBUTING.md
This PR updates documentation regarding 16 color codes in THEMES_CONTRIBUTING.md 
It states the 256 color codes and its equivalent 16 color codes to fall back upon (in case of color depth 16). Also, it adds a reference to urwid documentation of accepted 16 color codes and lists the accepted colors as well
Relevant link to CZO discussion - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/16-color.20names.20in.20themes
**Tested?** 
None. All changes have been made in accordance with the discussion on CZO
Independent PR
None
=> Updates documentation for 16 color names in THEMES_CONTRIBUTING.md

README.md, docs/FAQ.md, zulipterminal/config/themes.py
Some areas of documentation mention old theme names or do not include gruvbox_light.
This also documents the theme dicts in themes.py, to avoid future confusion over their use.
=> FAQ/README/themes: Update documentation to reflect current themes.

docs/FAQ.md
Now that we have a scrollable message view (i, f), we can now note that this would be useful for small terminals.
=> FAQ: Expand small terminal section to suggest scrolling long messages.

.github/workflows/lint-and-test.yml, README.md
We currently test PyPy 3.6-3.8; the first commit adds PyPy 3.9. Since it doesn't always have an lxml wheel available, these are installed manually in all cases of PyPy.
Given that supported Python versions are not clear from the icons or even `setup.py` exactly, a section is added to the README to note this, as well as a reference to #1145.
**Tested?**
=> Improve PyPy coverage in CI & Note supported Python versions in README

tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
Prior to this PR, if a message's topic was changed, the
corresponding `message_id` was not removed from the old topic's set
and added to the new one under the "topic_msg_ids" key of the model's
index. This PR updates the relevant sets to ensure accuracy.
**Tested?** 
- api_types: Include the orig_subject field in UpdateMessageEvent. 
This commit introduces another field to the UpdateMessageEvent class
in `api_types.py` to accommodate this field in the event handler
method for update message events.
- bugfix: model: Remove updated message_ids from their old topic's set.
Prior to this commit, if a message's topic was changed, the
corresponding `message_id` was not removed from the old topic's set
under the "topic_msg_ids" key of the model's …
=> Update index's `topic_msg_ids` accurately with topic updates.

tests/model/test_model.py, zulipterminal/model.py
This updates an approach taken in the original reaction implementation.
Since locally cached messages are currently stored in a `defaultdict`,
direct indexing with a non-present message-id creates an empty message.
Such messages then generate `KeyError`s when flags are updated later
(eg. marking read, toggling star status), if the message has not been
fetched.
Tests updated to explicitly exclude generation of empty index for
reaction events.
Fixes #920.
**Tested?** 
This suggests we should move away from `defaultdict` for at least this data structure, as access masks generation of invalid data.
This is purely a bugfix. This prompts thoughts on further refactoring, but an outstanding branch for improving reaction handling …
=> bugfix: model: Avoid creating empty messages from reaction events.

tests/ui/test_ui.py, zulipterminal/ui.py
This prevents rapid footer updates if an error message is triggered
multiple times. An example of this would be a user holding-down/pressing
too often the edit message key on a message that cannot be edited.
This fix does not account for updates that might happen for different
messages, but we can safely assume that the time difference between such
messages would not be too small and such a bug would most likely not
occur.
Test added.
Fixes #647.
=> bugfix: ui: Do not update footer if new text is same as current.

tests/conftest.py, tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
This primarily fetches and dynamically updates a user setting which optionally hides private message content from appearing in notifications.
This requires fetching a new category of data (in older servers), as well as handling the update of that data.
This user setting is, along with the 24h/12h setting in a refactor, in the new user settings structure added recently.
**Tested?** 
- Migrate 24h/12h setting into new structure (refactor)
- Do initial fetch of new setting
- Support updating of new setting
- Use new setting to control display of content
Settings will eventually be initialized and updated differently as per #1108.
=> Recognize setting for hiding of PM content in notifications

tests/config/test_themes.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py
In ``/zulip-terminal/zulipterminal/config/themes.py`` code is added in ``generate_theme`` function to check if valid color codes are used in color files for specific themes. For eg. (``colors_gruvbox.py`` for ``gruvbox_dark.py`` theme)
Fixes #1158 
**Tested?** 
=> Ensure color codes are valid at runtime if running in 16-color mode.

tests/model/test_model.py, zulipterminal/model.py, zulipterminal/platform_code.py
This is complementary to #1061, which is aimed at the message content and accessing the hidden content. #688 doesn't discuss the specifics, but hiding in notifications is one part of this. 
This PR migrates the html processing from the platform code into the model, where beautiful soup is used to translate and extract content accordingly.
Prior to this PR, spoiler text in a message gives rise to extra lines of text and doesn't hide the spoiler content. The updated output is intended to match the style from the web app, which translates a spoiler with a `title` and `content` into `title (...)` in a notification.
**Tested?** 
This provides good infrastructure for a follow-up set of work to explore how different markdown is rendered in …
=> Hide spoiler content in notifications

setup.py, zulipterminal/api_types.py
This bumps the versions of many of the project's dependencies.
Most of the install dependencies provide extra features or bugfixes, with the addition that the zulip package now incorporates some code that was previously defined locally so that can be refactored out. The only downside of the latter is that this is less explicit in our code, hence the minor additional comments.
Other than bumping linting dependencies generally, the upgraded `mypy` will allow for improving our use of `TypedDict`, among other possibilities. Additional typing dependencies should help; we could consider one for `beautifulsoup4`, but this requires further analysis so I've left it at this time.
**Tested?** 
There should not be any significant feature changes in the dependencies, so I …
=> Upgrade dependencies (install, dev, linting, dev_helper)

zulipterminal/ui_tools/boxes.py
If editing a message in a private stream (or soon, a web-public stream), the stream marker was not set correctly.
One commit adjusts this to do so correctly using the new helper method, while the other removes the duplicate code originally used prior to the helper method.
**Tested?** 
We could add tests for the stream marker/color setting in various edit modes - we have none currently. The marker/color behavior is tested separately using a test for the common helper method.
=> Bugfix to update stream marker/color on editing stream message

zulipterminal/themes/colors_gruvbox.py, zulipterminal/themes/gruvbox_dark.py, zulipterminal/themes/gruvbox_light.py
When the light variant was added, we noticed that the gruvbox palettes have the faded/neutral/bright variants of colors, and it was suggested to group these. 
It is noticeable in the palettes linked below that:
- dark uses bright+neutral colors
- light uses faded+neutral colors
The existing dark variant uses some faded colors, and the light variant seems to use some bright ones. This PR is intended to address these issues, and group colors to make this usage clearer.
https://github.com/morhetz/gruvbox#palette
**Tested?** 
- Update dark mode, and label/group used color palette elements
- Update light mode, and label/group remaining color palette elements
The term 'mode' is used in the color palette comments, based on the …
=> Use only colors from suggested gruvbox palettes

.mailmap
Tested using `git shortlog -s`.
Probably more tweaks can be made here; this is what I used for the Zulip 5.0 release.
=> git: Add .mailmap file to deduplicate contributors.

tests/conftest.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py, zulipterminal/config/symbols.py, zulipterminal/config/ui_mappings.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This is intended to fix most of #712 (#1135)
See #**zulip-terminal > Web public marker #T1135/#T712**
**Tested?** 
- Add model accessor for stream type, given stream id
- Use new accessor outside of model (in UI)
- Add fixtures for a web public stream & adjust existing tests
- Add symbol and extend existing code minimally to indicate symbol in most cases
- Add symbol rendering in stream list
- Refactor duplicated if/elif blocks to use new common dict in ui_mappings (descriptions)
- Refactor if/elif blocks to use same dict for icons too
This needs some tests fixed and I'm planning an additional refactor, but pushing now to get feedback.
**update** Tests are now fixed and extended.
Currently, web-public …
=> Indicate web-public streams differently

tests/model/test_model.py, zulipterminal/core.py, zulipterminal/model.py
This PR improves reporting upon moving a message by editing it's topic.
Partial fix for #1172 
**Tested?** 
https://user-images.githubusercontent.com/53873549/159926734-3f04ffb8-c35f-4836-8d76-ae7401e6fca6.mp4
=> model: Improve reporting upon moving/splitting topic.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This conditional appears unnecessary, and interception here can cause multiple triggers of the keypress in corner cases.
Test removed.
Discussed in #**zulip-terminal > Avoid double Esc keypress #T1201**
**Tested?** 
This appears to also resolve the outstanding issue with #1194.
=> views: Avoid sending GO_BACK to duplicate child widgets unnecessarily.

docs/hotkeys.md, tests/helper/test_helper.py, zulipterminal/config/keys.py, zulipterminal/helper.py, zulipterminal/ui_tools/boxes.py
This PR adds support to 'Narrow to current compose box recipient' after sending a message outside current narrow.
Shortcut - ``ctrl``+``.``
Fixes #1182 
CZO - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Support.20'Narrow.20to.20current.20compose.20box.20recipient'
**Tested?** 
Currently I have used shortcut - `.` instead of ``ctrl``+``.`` as ``ctrl``+``.`` doesn't seem to work in my local development environment (WSL2 Windows 10) 
=> Support 'Narrow to current compose box recipient'.

README.md
Document our use of `black` and `isort`.
**Tested?**
=> README: Add notes on using auto-formatting tools.

tests/core/test_core.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui/test_ui.py, tests/ui/test_ui_tools.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py
This PR highlights stream names in reporting of moving/splitting topic in footer text.
Partially fixes #1172 
CZO - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/.E2.9C.94.20Improve.20reporting.20on.20moving.2Fsplitting.20topics.20.23T1172.20.23T1178
New CZO - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Highlight.20text.20of.20reporting.20on.20moving.2Fsplitting.20topics
**Tested?** 
=> model: Highlight stream name in reporting of moving/splitting topics.

zulipterminal/core.py
These unrelated aspects being tied together was not an issue previously,
when narrowing was always done outside of compose. However, with
integration of #1194 as 2195904dd this is no longer the case, so this is
required to ensure that narrowing does not prematurely end editor mode,
since otherwise container widgets would steal keypresses.
This may be improved later through further refactoring of the keypress
handling.
**Tested?** 
Everything appears to work fine; as per commit description, we should fix this more cleanly with the keypress refactoring. See #**zulip-terminal > Keypress refactoring**
This resolves an issue triggered by #1194, but which was present previously and only triggered by this situation.
=> bugfix: core: Do not exit editor mode when narrowing.

tools/check-branch, tools/python_tools.py, tools/run-mypy
This is a first pass at a script to ensure a branch has commits which individually pass `make check`.
**Tested?** 
^ checked with this script!
This may become integrated into CI at some point, but an initial try at this turned out to be more complex than expected, so working with something we can easily run locally first.
I've not added documentation yet, since I'd like to let this get some simple testing first.
This script passes if it leaves you back at your branch; if it fails it leaves you at the failed commit, at which point you can `git rebase --abort` and explore it more yourself, or use the rebase interactively.
=> tools: Add check-branch to run 'make check' on all branch commits

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/boxes.py
Fixes #1212
This PR displays reacting usernames besides reacting emoji in messages.
CZO - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Feature.20discussion.20-.20Show.20usernames.20adding.20emoji.20to.20message
**Tested?** 
In Zulip web app -
In ZT -
=> Display names of reacting users when few users have reacted.

tools/font-styles-test, tools/gitlint-extra-rules.py, tools/run-mypy
- Run mypy on python tools/ by default (with exclusions)
- Switches the explicitly included running of mypy on test files to check into a shorter list of remaining test files to add typing for
- Refactoring
**Tested?** 
@prah23 Down to only two test files needing typing after last Summer :)
@mounilKshah This will affect the tool for docstrings in #1208; there are some types in that PR, but they won't be checked in CI until this is merged.
=> Run mypy on tools/ & close down list of checked tests/

tests/helper/test_helper.py, tests/platform_code/test_platform_code.py, tests/ui_tools/test_buttons.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/platform_code.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
This is a slight tidy and re-ordering of #1058, which itself has quite a lot of history via earlier PRs. I've left #1058 as it is right now, other than the changes I made semi-recently to make it cleanly mergeable via a rebase onto then-main. When this is merged then that and a few other PRs can be closed too.
This functions fairly well right now and fulfills a feature, though I can foresee quite a few updates following this, which I'll push out to another issue. For now I'm keen to get this merged.
**Tested?** 
I'd like to merge this very soon, but feedback is welcome, as it was on #1058 - the functionality should not have changed from that.
=> Media opening (slight reorder & tidy of #1058)

README.md
The *About* part of the README already has details of the project focus/scope, and features considered only for longer-term resolution.
This specifies other intentional design choices which might be useful, or cause users to stumble or being surprised if having used the web app.
Fixes #547 (Document intentional design choices where different from webapp/mobile)
**Tested?** 
I've noted down a set of elements that differ; we can amend these here or update them later. 
Related to #731, but that is for incomplete features which we intend to implement, rather than intentional choices to implement differently (or not implement).
=> README: Add intentional differences from web client to Feature status.

setup.py, tests/config/test_keys.py, zulipterminal/config/keys.py, zulipterminal/helper.py
- upgrade typing-extensions (for mypy + new features)
- upgrade mypy
- migrate away from total=False with the KeyBinding TypedDict, using NotRequired
- migrate asynch to use ParamSpec and clarify the return type
**Tested?** 
`typing-extensions` is upgraded first due to the mypy dependency, though is used in the application as a whole, rather than just development.
Similarly, the features depend upon the names being available, and mypy won't recognize the syntax in earlier commits if it is upgraded last.
There are a few other TypedDicts which total=False could be removed from, but these are potentially more complex (Message) or may have related open PRs.
=> Upgrade mypy to 0.960 & use new typing features

tests/conftest.py, tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
Migrates `in_home_view` to `is_muted` for Subscription.
Partially fix towards #965.
[#zulip-terminal>Update to modern API elements (support v2.1) #T965](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Update.20to.20modern.20API.20elements.20.28support.20v2.2E1.29.20.23T965)
**Tested?**
- First commit contains the UI changes for the migration
- Second commit contains changes made to the test functions
=> Remove support for Subscription["in_home_view"]

tests/ui_tools/test_boxes.py, zulipterminal/ui_tools/boxes.py
This PR improves stream sorting for stream typeahead in compose box stream results in footer in the following order -
1) current stream (if matching)
2) pinned and unmuted
3) unpinned and unmuted
4) pinned and muted
5) unpinned and muted
CZO - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Improve.20stream.20sorting.20for.20stream.20typeahead.20in.20compose.20box.2E
**Tested?** 
Passing all lint tests.
``test_generic_autocomplete_streams`` test to be updated in ``test_boxes.py``
Stream sorting for stream typeahead before -
Stream sorting for stream typeahead after -
=> ui/boxes: Improve stream sorting for stream typeahead in compose box.

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This is an adjusted version of the rebuild of #442 in #1239, so if merged will supersede both of those.
The motivation for this was upon considering the test adjustments which were absent in the draft updated PR (#1239), it seemed much more natural to migrate the appropriate function into the model itself. The main logic is therefore the same as #442, but the surrounding code is quite different, including tests.
I'm strongly considering merging this promptly, but I'd welcome a read-through, and testing by anyone who looked at #T1239.
This was discussed in #**zulip-terminal > Skip muted topics and streams on 'n' #T442 #T1239**
(may update topic name given this PR)
**Tested?** 
This explicitly adds what I believe is the current behavior of …
=> Skip muted topics and streams on n key

tests/ui_tools/test_buttons.py, zulipterminal/ui_tools/buttons.py
This PR creates TopButton attributes `prefix_markup`,
`label_markup` and `suffix_markup` with Type `urwidMarkupTuple`.
All of the other attributes can be written in terms of these
which simplifies the logic in various methods ad reads better.
This PR formed after splitting of the last commit of #1064 and is a follow-up to it.
**Tested?** 
**Commit 1-3**: refactors TopButton attributes.
**Commit 4**: button: Add muted style to stream prefix. 
The old attributes are kept and deleted in the following commits to keep the diffs cleaner and have separate commits.
I haven't handled the count Exception that happens because of `self.count`. I realize I shouldn't have removed it.
=> Simplify Topbutton attributes

.github/workflows/lint-and-test.yml, tools/generate_hotkeys.py, tools/lint-all
Fixes #1209
Adds GitHub Actions and changes to ``lint-all`` for linting ``generate_hotkeys.py``
**Tested?** 
=> hotkeys: Add linting for hotkeys.

.github/workflows/lint-and-test.yml
Adds the docstring linting from #1208 to CI, fully fixing #892.
**Tested?**
=> lint-and-test: Add job to run docstring linting.

tests/model/test_model.py, zulipterminal/model.py
This commit contains changes made to _handle_subscription_event() for handling is_muted events added under ZFL 139. Fixes #1251.
This PR adds support for `is_muted` events as a consequence of ZFL 139.
Fixes #1251 
[Update to modern API elements #T965 #T1236 #T1237](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Update.20to.20modern.20API.20elements.20.23T965.20.23T1236.20.23T1237)
**Tested?**
- This commit adds support for `is_muted` event
**Notes & Questions**
- Currently, `in_home_view` and `is_muted` are being supported by the server. However, as per ZFL 139, `in_home_view` shall be deprecated in the future.
=> Add support for is_muted event

zulipterminal/model.py
Currently, zulip-terminal is checking for the string "Bad event queue id:" to check whether an error is due to a bad event queue ID. This is not the correct algorithm; as documented on https://zulip.com/api/register-queue, it should be checking the code on the response object, not the msg field.
Fixes #1272
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/events.20error.20handling
**Tested?** 
- First commit, changed `msg` field to `code` field in response object and changed matching text accordingly
- Not sure how I'd test the working of this manually. 
=> model: checking 'code' field instead of 'msg' field

.github/workflows/lint-and-test.yml, setup.py
Initial local testing with Pipenv on x86_64 glibc seems to indicate the application runs on Python 3.11, so let's enable CI to (start to) prove it.
Follow-up from [CZO thread](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Python.203.2E11.20support/near/1478433)
=> ci: Provide initial Python 3.11 testing support.

.github/workflows/lint-and-test.yml
Explore change to do tests on the macos platform against the latest available CPython.
This follows the discussion on adding support for Python 3.11 here:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Python.203.2E11.20support/near/1478470
**Tested?** 
(CI change)
Depends on #1276 since the latest version on macos is automatically installed properly and is actually 3.11; the last commit here can be removed after that is merged.
=> lint-and-test: Use latest default CPython on macos.

README.md, tests/cli/test_run.py, zulipterminal/cli/run.py
This is motivated by #**zulip-terminal > zuliprc template in README** (Summer 2021), as well as #1269 recently - namely that the zterm configuration section of the zuliprc used by ZT as documented in the README could be improved and more cleanly defined/annotated.
In particular, the above discussion and issue relate to where both footlinks and maximum-footlinks options are present (uncommented) in a zuliprc file at the same time, which `zulip-term` knows are incompatible - and so outputs a rather terse error message.
This PR approaches this on two fronts, as two commits:
- improve the example zuliprc file in the README, such that the zterm settings relate to default values that both fundamentally work if copy/pasted, and are better documented
- adjust the error …
=> Improve documentation of zuliprc as used by zulip-term

docs/FAQ.md
This was motivated by a realization that we don't explain footlinks except in the CHANGELOG, and a query regarding how to open images and similar.
(see https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Q.3A.20Opening.20images.3F
ie. #**zulip-terminal > Q: Opening images?**)
This PR introduces a single section, then adds subsections for how footlinks are constrained in the message list, and how the full link data is available in the message information popup.
This expands upon a pre-existing FAQ entry regarding how footlinks are shown, which is removed.
**Tested?** 
@Sushmey pointed out as feedback that the reference to images is not as clear as it could be, though is mentioned in the last subsection, which doesn't stand out …
=> Create FAQ section explaining footlinks and how to access the links (attachments, internal links, external links)

.github/workflows/lint-and-test.yml, tests/cli/test_run.py, zulipterminal/cli/run.py, zulipterminal/platform_code.py
This outputs the platform we detect, before ZT starts. The benefit of this is that it is clear if the platform is unsupported, and also should form part of the feedback we receive from users in bug reports.
This also checks the detected platform during CI, to ensure we test code paths there, as far as we can.
**Tested?** 
**Notes & Questions (maybe further work)** 
- We could output an additional warning if it is unsupported, but this is a good first step to aid in helping users.
- We don't currently test on WSL to ensure we detect that correctly, or on some other unsupported platform to ensure it's flagged too.
=> Show detected platform on startup and during CI

setup.py, tests/model/test_model.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_buttons.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
This results in minor removal of blank lines at start of blocks.
The previous >=22.1.0 versioning worked fine until version 23+ was released,
which required these changes. This was not noticeable on already-installed
systems, but can trigger in updated/new dev environments, including when
testing in GitHub Actions (CI).
The requirement change to ~=23.0 should maintain stability for 2023 releases of black.
(https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy)
**Tested?**
=> Upgrade black from >=22.1.0 to ~=23.0 & reformat.

docs/FAQ.md, docs/developer-feature-tutorial.md, docs/developer-file-overview.md, docs/getting-started.md, zulipterminal/ui_tools/buttons.py
Primarily:
- Expand/clarify the autocomplete section
- Include the web-public marker
- Improve introduction (motivation) for autocomplete
- Style hotkeys using kbd
- Expand the PMs abbreviation into Private Messages
- This is something of a prep for #1288, at least in documentation.
**Tested?**
=> Docs: Improve autocomplete docs & expand PMs to Private Messages

setup.py, zulipterminal/cli/run.py, zulipterminal/ui_tools/boxes.py
Bumps mypy version to 1.0.0 and makes minor changes to remove some type ignores, one of which caused a linting error.
The commits are structured to bump mypy first, since it seems that lots of type stubs became incompatible with mypy < 1.0 in python/typeshed#9702, which I assume translated into an incompatible `types-requests`. This translates into 2 `Self?`-related errors in ZT, maybe more elsewhere.
The second commit then makes some minor adjustments to take into account the mypy bump. These are only typing changes (or ignore-comments) so should not substantively affect the code running, though arguably they do fix the previous commit. I'm keeping them separate for clarity.
**Tested?**
=> Upgrade to mypy 1.0.0 after incompatible typeshed change

pyproject.toml, tests/config/test_themes.py, tests/model/test_model.py, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py, tools/fetch-unicode-emoji-data, tools/gitlint-extra-rules.py, tools/lister.py, tools/run-mypy, zulipterminal/cli/run.py, zulipterminal/config/color.py, zulipterminal/config/regexes.py, zulipterminal/config/themes.py, zulipterminal/helper.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/views.py
Adds more linting via flake8-like behaviors which are integrated into ruff:
- B: flake8-bugbear
- C4: flake8-comprehensions
- UP: pyupgrade
- RUF100: unnecessary noqa
- T20: flake8-print
- PGH: pygrep-hooks
- PLC, PLE, PLW: pylint convention, error & warning checks
- ANN: flake8-annotations
- YTT: flake8-2020
As with the migration to ruff, some files are excluded, generally or just temporarily.
Linters are enabled individually; note that some require no changes right now but are likely of interest, while others require minimal changes which are included in the same commit or prior commits.
NOTE: These additions take *very little* extra time, which is great for the extra checks we enable! In addition, *some* of these can be fixed automatically by ruff (or via …
=> Enable more ruff linting

.github/workflows/lint-and-test.yml, pyproject.toml, setup.py, tests/model/test_model.py, tools/lint-all, tools/lint-docstring, tools/run-codespell, zulipterminal/config/color.py, zulipterminal/core.py, zulipterminal/platform_code.py, zulipterminal/server_url.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/views.py
To follow up on a remaining element of #508, this adds `codespell` as a local configured tool via a wrapper, which also runs in CI.
Commit-wise, a few small language changes are made, before the tool is then installed, wrapped and configured in pyproject.toml, then integrated into local and CI tools.
**Tested?**
=> Add codespell linting

.github/workflows/lint-and-test.yml
- Python 3.6 support was otherwise removed from testing in 926fc4c96.
- Errors are being reported since codecov has upgraded and the node version is different.
An earlier commit removed support for python3.6 in CI (now over a year past EOL), but PyPy was missed in this transition.
Note that the documentation is not updated to state that support has been removed for 3.6, simply that we are no longer testing against it.
**Tested?**
=> Remove support for testing PyPy 3.6 & bump codecov action

.github/workflows/lint-and-test.yml
Groups CI (GitHub Actions) jobs, so that sets of jobs must complete before others.
Currently all jobs run independently, which means that even if linting fails then we still pytest on every platform, and vice versa (assuming no other issues). That shows clearly where the problem is, but running pytest on every python+platform is something we likely should only do once the code passes simpler checks. This would minimize resources spent on spinning up various parts of CI, but also may present a simpler view to devs.
The other feature included here is an intermediate dependent stage to check for commit isolation, using the tool `check-branch` added in #1214.
**Tested?** 
**Edit** The last commit is now updated to only run the per-commit …
=> Reduce unnecessary CI jobs (dependencies) & check commit isolation

pyproject.toml, setup.py, tests/config/test_color.py, tests/config/test_themes.py, tests/model/test_model.py, tests/platform_code/test_platform_code.py, tests/ui/test_ui_tools.py, tools/generate_hotkeys.py, zulipterminal/api_types.py, zulipterminal/cli/run.py, zulipterminal/config/ui_sizes.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/platform_code.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/messages.py, zulipterminal/urwid_types.py
This makes various smaller fixes to enable enforcing linting of names according to the `N`aming rule in ruff.
This doesn't find any specific bugs, but does lead to centralization of some constants that were localized in the code itself, and could be centralized further - as other ruff rules may suggest later.
This also drops the `test` command in `setup.py`. This is now deprecated in `setuptools`, and we've not been actively promoting it as far as I'm aware.
**Tested?** 
While by no means as large an issue as in zulip/zulip, this PR takes the same approach of delaying applying the exception-naming standard of an `Error` suffix for later, to get this rule in place first. That could also be a good first issue to explore.
=> Enable checking of naming rules using ruff

.github/workflows/lint-and-test.yml, tools/check-branch
PR #1310 demonstrated an issue with the new isolation-checking part of the CI.
The `make check` command implicitly part of the `check-branch` tool was updating an installed venv, as it does locally, but this venv is not activated. Instead the packages from the previous job step were being used throughout the isolation checking process.
This PR takes one approach at resolving this, explicitly installing packages at each commit before running the checks, after enabling this feature in `check-branch` in the first commit.
**Tested?** 
This approach is not as optimal as the implicit `make venv` done locally, which only updates the package install if the dependency file changes (currently `setup.py`). For now, fixing CI is the priority and this …
=> Bugfix: Update dependencies per-commit during isolation checks in CI

pyproject.toml, tests/emoji_data/test_emoji_data.py, tests/ui_tools/test_boxes.py, tools/generate_hotkeys.py, zulipterminal/core.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/scripts/render_symbols.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/utils.py, zulipterminal/ui_tools/views.py
This makes changes associated with the SIM rules in ruff, which are recommended simplifications.
This excludes SIM108 (prefer ternary if-else), as in zulip/zulip, though other changes may be necessary in time.
As per other PRs adding rules to be checked, this is a set of refactors, followed by enabling of the rule with some noqa changes. This ensures commit isolation, including that noqa lines are not flagged as unnecessary before the associated rule is enabled.
**Tested?**
=> Enable checking of Simplication rules using ruff

README.md, zulipterminal/cli/run.py
This was motivated by a point of confusion regarding the meaning of 'Zulip URL' at https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Zulip.20url, hence a commit to synchronize the text in the README and code.
Before doing so, this reformats the early sections of the README to make them more readable without line wrapping, which makes `git diff` and `tig` a lot more usable.
While looking at this, I noticed some improvements/clarifications to make, so there are commits to restyle a few parts and to expand upon the section on keeping an install up to date.
**Tested?**
=> Improve various README text & use 'Zulip server URL' consistently

tests/cli/test_run.py, zulipterminal/cli/run.py
This is a small refactor followed by a change which should fix #1318.
This uses the server settings we fetch in any case, to use the preferred URL from the server as per the `realm_uri` field.
**Tested?**
=> Bugfix: Respect the server's choice of URL when fetching api key

pyproject.toml, tests/config/test_color.py, tests/config/test_themes.py, tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
This addresses the change in API behavior in update_stream introduced at ZFL 152, essentially requiring additional parameters to retain the previous behavior.
(ref https://zulip.com/api/update-message#parameter-send_notification_to_old_thread)
Prior to this change, another test for the same function is simplified and test-case ids added.
Further, to allow various names in the new function, the ruff exclusion list for naming linting is first updated to allow mixed case in general in tests/*.
After these changes, a commit applies typing to these parameters as defined at the above URL.
**Tested?** 
- Passing these parameters to the API will be necessary to use the new functionality in future, which this change enables
- This PR leaves topic …
=> Normalize update_stream_message behavior regarding notification messages

README.md, docs/FAQ.md, docs/developer-feature-tutorial.md, docs/developer-file-overview.md, docs/getting-started.md, docs/hotkeys.md, tests/model/test_model.py, tests/ui_tools/test_buttons.py, tests/ui_tools/test_messages.py, zulipterminal/config/keys.py, zulipterminal/model.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/messages.py
This PR replaces instances of 'private' with 'direct', in the context of private messages, in the UI and relevant docs.
This is in line with the design decision to rename private message (PM) to direct message (DM).   
Fixes #1288 
[CZO Discussion Link](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/'private'.20to.20'direct'.20.23T1288)
**Tested?** 
- First, second and fourth commits change UI elements from 'private' to 'direct'.
- Third and fifth commits update the documentation.
- Some UI changes like the keybinding help texts in the second commit do not result in test failures. Do we need to add tests for them?
=> Migrate UI & Docs from Private to Direct phrasing

tests/ui_tools/test_messages.py, zulipterminal/config/themes.py, zulipterminal/core.py, zulipterminal/themes/gruvbox_dark.py, zulipterminal/themes/gruvbox_light.py, zulipterminal/themes/zt_blue.py, zulipterminal/themes/zt_dark.py, zulipterminal/themes/zt_light.py, zulipterminal/ui_tools/messages.py
This adapts the last commit of #1012, which was neglected while discussing how to handle the padding/blocking of codeblock rendering.
The change is now in messages.py, but works well after a manual movement.
The associated removal of `msg_code` is split into a second commit which instead renames the style to `ui_code`, since it is still used in a notification popup. This could have been migrated to use the pygments style too, but for now it feels cleaner to keep pygments within the message rendering functionality, and not hard-code the style elsewhere.
**Tested?**
=> Style inline code like code blocks (via #1012)

.github/pull_request_template.md
This adjusts the PR template to look roughly like in this Pull Request (small updates made later).
This was motivated by the testing section being somewhat redundant due to CI now testing for isolated commits, and grew from there.
The main changes are:
- Simplifying titles contributors see while editing via ### instead of bold
- Adding 'and why' to the 'What does this PR do?' top title
- Updating the 'Tested?' section to be 'How did you test this?'
- Generally clarifying each entry
- Manual checks split into behavioral and visual entries
- 'Linting and tests per commit' removed in favor of a refactor-only entry
- Adding a self-review checklist (for each commit) to emphasize expectations
- Adding an 'External discussion & connections' section with checkboxes
- The comments re including …
=> pull_request_template: Update and improve PR template.

tools/lint-all
This is a small change, but with a potentially large impact if running lint-all frequently.
By running more important, faster checks first, feedback is given to the developer sooner when failures occur.
In addition, this addresses two specific issues:
- ruff and black appear to disagree in some cases; running them first makes that faster to resolve
- isort gives less specific feedback on error locations than black (or ruff) when there are syntax errors, so if isort is first and fails, causing linting as a whole to fail, then that information is not available
The tools most likely to trigger failures are now run in order of the fastest tool first, ie. starting with:
- ruff (check) [was 3rd]
- black (check) [was 4th]
- isort (check) [was 1st]
- mypy [was 2nd]
Spelling and code-document …
=> lint-all: Reorder linting for faster development cycle.

tests/cli/test_run.py, zulipterminal/api_types.py, zulipterminal/cli/run.py
This follows up on the bugfix of #1320, now introducing and applying types for the server-settings response.
Also following from #1320, this aims to give the user more accurate feedback and exit cleanly (cf the current confusing message(s) or tracebacks) if the server URL is not recognized as corresponding to a valid Zulip Organization.
Some of this is a little WIP, since the documentation on the server-settings endpoint is a little confusing, but this is close to mergeable.
This aims to work further towards separating the text input and the logic, as well as improving the testing.
**update**
- This is now tidied, and resolved an issue experienced in [**#zulip-terminal>Crash on entering bad server URL**](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/t …
=> Improve URL error-handling prior to zuliprc generation

README.md, docs/FAQ.md
This updates the contributor and FAQ documentation
- line-wraps the README contributor section (making updates clearer)
- fix a few broken links
- update the FAQ section regarding supported newer python versions
The latter broken behavior similar to #1145 should not reoccur, since 0.2.0/0.2.1 have been yanked from PyPI.
Thanks to @theViz343 for pointing out one broken link, which I've included here :+1:
=> Fix contributor links & update note re installation with new Python versions

tests/core/test_core.py, tests/helper/test_helper.py, tests/model/test_model.py, tests/ui_tools/test_messages.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/messages.py
Fixes #1351
**Tested?** 
This is divided into 3 commits.
1. Refactor in `model.py`
2. Refactor in `helper.py`
3. Refactor in `messages.py`
Commits are independent of each other 
With these changes, the user_list and the `z` toggle on messages work as earlier.
=> Refactor: change pm_with to pm-with

tests/conftest.py, zulipterminal/api_types.py, zulipterminal/model.py
Message type was previously only typed as `str`, whereas Zulip specifically only has the two types `private` and `stream` (for now). This will be changing soon to migrate `private` to `direct`, though will remain backwards compatible for a long time.
This upcoming change partially motivated the above, but related conversation discussed the typing notifications also migrating, which was also not previously typed in the ZT code.
Other constants relevant to the API were also migrated in a third commit.
=> Add typing for MessageType & typing notifications

.editorconfig, README.md
EditorConfig is rather useful - standardized basic formatting and a few other goodies.
See editorconfig.org, or the note added to the README here.
This may depend on your editor - in vim I get a nice red column for the maximum line length :)
=> README/editorconfig: Add .editorconfig to improve editing consistency.

tests/ui/test_ui_tools.py, zulipterminal/ui_tools/views.py
This is expected to be a bugfix for a missing part of the refactor in #1393, which causes a crash with no unread messages, as pointed out by @theViz343 :+1:
This fix was delayed due to observing other issues, which took longer to fix so are now deferred to another PR.
=> Bugfix for previous refactor

zulipterminal/api_types.py, zulipterminal/model.py
This is a follow-up to #1384, reusing a typing notification literal in an event, and then applying similar principles to other events. This includes extracting some dicts to use to improve the calls to the API, which are often very similar, and otherwise currently untyped dicts.
This also adds some much-needed commented sub-structure for events, which now have various associated dicts or literals, and links to the appropriate place in the API docs.
=> Improve event API typing & apply to model

docs/FAQ.md
Currently this PR improves the accessibility and structure of what is an increasingly large FAQ, by adding a (manual) table of contents, with entries grouped into categories, with some section titles renamed.
This also performs a similar line-wrapping as applied to other documentation, to make editing and changes clearer in larger paragraphs/sentences.
Added table of contents with categories and new section titles:
=> Add FAQ table of contents and restructure

tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
This bug was identified via the additional flags added in comments in #1401.
Previously the is_me_message flag in messages were not updated locally, if the content was updated to be recognized as such by the server. Such a flag is provided directly in update_message events (is_me_message) as in message objects fetched from the server, but was not synchronized until now.
This had no effect on /me messages which were edited to lose that status, since the message rendering code did not find the matching /me message content and so updated the rendering to show as a regular message.
However, for messages which were initially not /me messages, the /me rendering path could never be entered if they were subsequently edited to become /me messages, since the property of the message was not updated …
=> bugfix: Correctly rerender when /me status changes.

docs/hotkeys.md, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/views.py
This PR adds functionality which displays user information for the sender of a message when the 'u' hotkey is pressed on an active message box. This would match the behavior in the web app.
=> Displays user information for sender of message on u hotkey

tests/config/test_themes.py, zulipterminal/cli/run.py, zulipterminal/config/themes.py
This was motivated by exploring adding support back for transparency (across themes) and considering the tests and runtime checks currently in place for theme specifications.
This PR primarily involves:
- adding tests for existing theme completeness/loading behavior
- clarifying conditions for if a theme is complete
- reporting errors in theme definitions which previously resulted in tracebacks
- explicitly giving errors if required elements of a theme are absent
As a result this:
- enables safer refactoring (including in this PR)
- provides the foundation to extend theme handling (such as for transparency)
- better defines expectations of what is necessary in a theme (via tests & at runtime)
- supports simpler theme contribution
Currently:
- Incomplete themes are those lacking a `Color` …
=> Themes: Improve completeness checking & runtime validation

tests/conftest.py, tests/model/test_model.py, tests/ui_tools/test_popups.py, zulipterminal/api_types.py, zulipterminal/helper.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This PR adds custom profile fields to the user info popup, which previously only displayed basic user information. This will include information about the user which, currently, has to be accessed by using the webapp. This PR also adds update event handling for the custom profile data.
=> Load and show custom profile fields in user information popup

tests/conftest.py, tests/ui_tools/test_messages.py, zulipterminal/config/symbols.py, zulipterminal/ui_tools/messages.py
Adds prefix icons to currents message headers
There are other parts of the ui that also needs the prefix icons but the person who opened the issue said that each section could be done with multiple pull request so that is how I chose to do it.
--speeding-up-reviews-merging--development) (title & body)
=> Adding prefix icons to current message headers

tests/model/test_model.py, tests/ui/test_ui_tools.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
This PR improves the algorithm for the 'next unread topic'  method used as the 'n' keybinding. It replaces the use of the last unread topic with the topic of the currently selected message to determine the next unread topic to cycle to. 
[![Demo](https://asciinema.org/a/XFCM5cH7W0FHaTNbkj1dGQ71S.svg)](https://asciinema.org/a/XFCM5cH7W0FHaTNbkj1dGQ71S)
=> Improve algorithm for 'next unread topic' (n) to use current message state

docs/hotkeys.md, zulipterminal/config/keys.py, zulipterminal/ui_tools/views.py
It enables a key press shortcut using '=' to toggle the first emoji reaction on a message if there is one.
- I would appreciate feedback on if the coding style is acceptable.
Visual Test:
https://user-images.githubusercontent.com/55665883/232629469-830cf284-15f4-471c-805a-a93a0e087066.MOV
=> '=' keyboard shortcut for reaction agreement

tests/ui_tools/test_buttons.py, zulipterminal/ui_tools/buttons.py
This PR contains commit which extends support to the old format for narrow links 
which existed before server version 2.1.0
[#zulip-terminal > Support old narrow links format #T1422 #T1424](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Support.20old.20narrow.20links.20format.20.23T1422.20.23T1424)
[#api-documentation > Narrow URL formats](https://chat.zulip.org/#narrow/stream/412-api-documentation/topic/Narrow.20URL.20formats)
=> Add support for old format for narrow links

pyproject.toml, setup.py, tools/run-spellcheck
Other than keeping `codespell` and `typos` up to date with any extra spelling suggestions, the new version of `typos` allows configuration in `pyproject.toml`. Previous typos-specific workarounds were possible if adding a dedicated `typos.toml`, which I thought we'd previously added but avoided, which was the original motivation for looking at the latest typos version.
The pyproject.toml configuration is actually required for the upgrade due to `O_WRONLY` now appearing as a false positive. However, this also allows checking of the FAQ by typos, which was previously excluded from both tools due to the presence of `iterm`, by extending the allowed words list.
Ideally this would be simpler if tools added inline ignores (crate-ci/typos#316, codespell-project/codespell#1212), particularly if …
=> Upgrade spellcheckers

zulipterminal/core.py
Displays a confirmation popup when the (^C) interrupt signal is encountered, seeking confirmation prior to exiting the terminal client.
https://github.com/zulip/zulip-terminal/assets/110327345/f95a3f00-88ec-40cb-91ae-5ec8890a5985
=> Added Exit Confirmation Popup

tests/ui/test_ui_tools.py, zulipterminal/ui.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/views.py
-> This PR is based on the idea that just like a topic is always coupled with a stream, a stream can also be coupled with a particular a topic that was last focussed.
-> it solves the maintaining of focus of the topic list of a stream( say stream 1) from where the t button was pressed.
`api_types`: added new field "curr_topic" to Subscriptions
`buttons`: fill the `curr_topic` with topic button's name when `t` is pressed
`views`: In` TopicsView` when the view is created make the `"curr_topic"` focussed. (This would make the implementation work even if the topic list is rearranged as it depends on topic_name not the pos on the list)
`test_ui_tools`: change `self.view` to be a `MagicMock `object as `Mock `object is not subscriptable. …
=> [WIP] Maintain position in topic list when toggling topic list

tests/helper/test_helper.py, tests/model/test_model.py, zulipterminal/helper.py, zulipterminal/model.py
This PR sorts the list of unread topics using stream name instead of stream id. This makes the order of moving between streams similar to that in the left panel.
[![asciicast](https://asciinema.org/a/ML0Qj2WTSh5krcyCILzyzqdnv.svg)](https://asciinema.org/a/ML0Qj2WTSh5krcyCILzyzqdnv)
=> Use stream name instead of stream id to order unread topics in the next_unread_topic_from_message_id algorithm.

zulipterminal/config/symbols.py, zulipterminal/config/ui_sizes.py, zulipterminal/ui_tools/buttons.py
Adding symbols to narrow buttons on the top left of the side UI. This is to improve UI visually.
- [x ] It contains test additions for any new behavior
Before:
After:
=> Narrow symbols

setup.py
This is intended to provide a temporary quick fix for #1431, to enable the themes to continue working for now with `main`, by pinning pygments at ~=2.15.1.
=> bugfix: Pin pygments pending improved conversion to urwid

.github/workflows/lint-and-test.yml, tests/cli/test_run.py, tests/ui_tools/test_popups.py, zulipterminal/cli/run.py, zulipterminal/platform_code.py, zulipterminal/ui_tools/views.py
This was motivated by confirming which python was being used for running ZT, originally in the context of testing locally with python 3.12 and others (eg. for #1379).
Having this information included is also useful to users, as well as for having feedback from them. Initial console output is therefore updated to show this, and included in the About popup in a new Detected Environment category, including the platform - which resolves the last part of #1216.
In much the same way as the detected platform, a test step is also added to CI to ensure that the expected python version matches that detected.
Note that this includes the platform (CPython vs PyPy), and if present the branch - which appears to be where the PyPy implementation version is stored.
This also includes an infrastructure …
=> Extend platform detection to include details of python

tests/ui_tools/test_popups.py, zulipterminal/core.py, zulipterminal/ui_tools/views.py
Tests updated.
Added the Exit confirmation setting to the AboutView popup.
=> Updated the AboutView popup with Exit confirmation setting

tests/ui_tools/test_messages.py, zulipterminal/ui_tools/messages.py
Makes the @topic mention behave like user mentions and user group mentions.
Before Change:
After Change:
=> Visual fix @topic mention

tests/ui_tools/test_popups.py, zulipterminal/ui_tools/views.py
This is a minimal bugfix for the change to the API at Zulip feature level 226, ie. from Zulip 7.5 upwards, including Zulip 8.0.
Without this bugfix, ZT crashes upon opening the stream information popup for these recent server versions.
For now this reports that the email address is not available and disables the copying of the email address, if the field is absent.
To enable testing across feature levels, this adds some basic tests which are later built upon, and which could be used elsewhere.
Discussion:
- https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Stream.20Information.20ZT.20Crash
- https://chat.zulip.org/#narrow/stream/378-api-design/topic/Removing.20.60email_address.60.20from.20subscription.20objects.3F/near/1683612
=> Bugfix: Workaround no stream email from zfl226

setup.py
This works around a CI failure with PyPy 3.7, which occurs with the latest 5.0.1 release.
The exact error is
```
TypeError: inheritance from PyVarObject types like 'str' not currently supported
```
Limited time was spent debugging this, since Python 3.7 support will be dropped soon.
=> Fix pypy37 CI failure by pinning lxml~=4.9.2

setup.py, tests/config/test_themes.py, zulipterminal/config/themes.py
Pygments 2.16.0 introduced a style to support a combination of bold and italic styling in pygments/pygments#2444. Both of our gruvbox themes and the light native theme gain a 'bold strong' style via pygments as a result, which urwid fails to parse and blocks the application from loading.
This work would represent a clean fix for #1431, which was temporarily fixed by pinning pygments at ~=2.15.1 in #1433. Pygments can be unpinned after this fix.
Add method `translate_styles` that manually converts the pygments `bold italic` style into the urwid-compatible `bold, italics`. 
In requirements, unpin pygments from `~=2.15.1` to `>=2.14.0,<2.18.0`.
=> config/themes: Convert pygments styles to urwid compatible styles.

zulipterminal/ui_tools/views.py
Fixes #1453 
Discussion:
https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/ZT.20crashes.20when.20pressing.20.22c.22.20in.20empty.20stream
- [] It contains test additions for any new behavior
=> Bugfix: Avoid crash when "c" is pressed in Empty Narrow

tests/model/test_model.py, tests/ui_tools/test_boxes.py, zulipterminal/api_types.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py
As introduced in ZFL 204/Zulip 8.0, the typing duration values should no longer be hardcoded into the clients, and the server will provide those values. In case the values are not present, the previous defaults are used. I have also added tests to check for this behaviour.
=> Feat: Respect Server Typing Duration Settings & Tests

.github/workflows/lint-and-test.yml, pyproject.toml, setup.py, tools/convert-unicode-emoji-data, zulipterminal/cli/run.py
This results in a more featureful, fast and less buggy version of mypy - it certainly appears to be faster so far.
This PR upgrades mostly by individual minor versions, to incorporate minor fixes found to be necessary for each upgrade.
This also refactors the lint-and-test workflow to use a common python version for linting explicitly, which is then easily bumped to 3.8 for mypy 1.5.x.
The initial commit is a CI bugfix to enable the test minimal-dependencies for mypy, added in #1461.
=> Upgrade Mypy from 1.3.x to 1.8.x

tests/core/test_core.py, zulipterminal/core.py
ZT crashes on MacOS when opening a message in browser due to an attribute error, where it tries to get 'name' to display the browser name. This might be an issue for other OS too.
Also refactored the test function name, since it had an extra '_'
=> ZT crashing when viewing a message in the browser.

tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py
Instead of hard-coded constants, uses server provided values, falling back to the original constants when server version is lower.
=> Support server-customized presence parameters.

zulipterminal/core.py
Uses a constant to store the scroll prompt, and reuses in all popup headers.
=> Use a common scroll prompt in popup headers

tests/model/test_model.py, zulipterminal/api_types.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py
Introduction of the read_for_sender flag.
=> Added the read_by_sender 

zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
Adopts urwid_readline.ReadlineEdit for all the editors in Zullip Terminal.
The panel search boxes are the only remaining editors not using urwid_readline.ReadlineEdit.
=> boxes/views: Adopt urwid_readline for all editors.

.github/ISSUE_TEMPLATE/01_crash.md, .github/ISSUE_TEMPLATE/02_bug.md, .github/ISSUE_TEMPLATE/03_parity.md, .github/ISSUE_TEMPLATE/04_platform.md, .github/ISSUE_TEMPLATE/config.yml
This converts the basic issue filing system to use the GitHub template chooser.
The main feature at this point is to focus reporters on the scope of the issue:
- major bug (bug: crash)
- bug (bug)
- missing Zulip feature (missing feature)
- general feature/improvement (enhancement)
These should apply a corresponding default label to the issue, with the idea that this would provide an initial structure to fine-tune the labels, eg. a specific `parity` label to add to `missing feature`, which could also gain one of the `user` or `admin` sub-labels.
This already feels like an improvement over the current single blank 'template', though it may take time to see how it works in practice.
This takes some ideas from zulip/zulip#26000 and followups.
- How do these categories look like, if you were …
=> github: Add simple issue templates & configuration

.gitlint
This was motivated by the failure of a CI run on #1494, where I added a URL to the commit body.
This does not resolve issues for all previous commits where the B1 rule of long lines in the body would fail, but will allow some obvious common cases to pass.
Inspired by jorisroovers/gitlint#255, this should cover at least lines starting with:
- http or https [where URLs can be long]
- Co-authored-by: [where emails/names can be long]
The downside to this rule is that the line numbering is apparently offset, based on the gitlint documentation.
(https://jorisroovers.com/gitlint/latest/ignoring_commits/)
This was tested manually on the last 1500 commits on `main`, and limits the number of gitlint errors as expected for URLs. No changes are noted for Co-authored-by: at this time.
=> gitlint: Add regex to ignore some long lines.

docs/hotkeys.md, zulipterminal/config/keys.py
Improves the usage of urwid_readline hotkey commands.
Now that all editors support readline shortcuts after the merge of #1492,
all the readline shortcuts have been grouped into their own category.
Add missing key combinations, commands.
Re-categorize, re-order the keybindings.
Improve the help texts.
=> Improve the handling of editor actions as a help category

docs/hotkeys.md, zulipterminal/config/keys.py
Improves the conformity of help descriptions.
[ ] Usage of 'the' needs to be made uniform too. This has not yet been addressed.
=> Standardize hotkey help text

docs/hotkeys.md, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/ui_tools/views.py
Adds hotkey 'c' to copy information from the about popup. It's copied in this format:
```
Zulip Terminal: 0.7.0+git
Version: 9.0-dev-3226-gbc50a9743b
Feature level: 265
Theme: zt_dark
Autohide: disabled
Maximum footlinks: 3
Color depth: 256
Notifications: disabled
Exit confirmation: enabled
Platform: WSL
Python: 3.10.12 (CPython) 
```
| Before | After |
|--------|--------|
| ![image](https://github.com/zulip/zulip-terminal/assets/110327345/75fb979f-32dc-4818-b9bc-a25515cb48fe)| ![image](https://github.com/zulip/zulip-terminal/assets/110327345/6c37d8db-0743-4a50-a97e-1d036f61bdc6)|
=> Functionality to copy information from the about popup

docs/hotkeys.md, tests/ui_tools/test_boxes.py, tests/ui_tools/test_buttons.py, tests/ui_tools/test_messages.py, tests/ui_tools/test_popups.py, zulipterminal/config/keys.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/buttons.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/views.py
Breaks down the broader ENTER command into more specific commands.
- ACTIVATE_BUTTON
- EXECUTE_SEARCH
- NEW_LINE
This would enable using more specific help texts, categories and context.
And clarifies the purposes of the key better.
Updated the usage of each command in the UI tools.
Tests and docs updated.
The NEW_LINE command would also allow us to create a new user setting, where `ENTER` key and `Meta`+`Enter` can be switched between entering new lines and sending messages.
- Need to consider the placement of the new commands within their categories in the Help Menu.
- `Ctrl`+`M` can work as `Enter` too. This has not yet been addressed.
=> Break down the generalized ENTER command

docs/hotkeys.md, tests/ui/test_ui_tools.py, tests/ui_tools/test_boxes.py, tests/ui_tools/test_popups.py, tools/lint-hotkeys, zulipterminal/config/keys.py, zulipterminal/model.py, zulipterminal/ui_tools/boxes.py, zulipterminal/ui_tools/views.py
Breaks GO_BACK command into the following commands:
- CLEAR_SEARCH (clears search box and search list of current panel)
- EXIT_COMPOSE (clears compose box state and closes it)
- EXIT_POPUP (closes the currently open popup)
This would enable using more specific help texts, categories and context.
And clarifies the purposes of the key better for users and developers.
I've kept these as separate commits for the sake of readability. Introducing each command in its own commit, then finally removing GO_BACK command.
I could break #1497 into commits similar to this one for readability, if necessary.
I've kept this as a separate PR as it's an independent change, even though the motivation is shared.
=> Break down the GO_BACK command into separate commands

docs/hotkeys.md, tests/ui/test_ui.py, zulipterminal/config/keys.py, zulipterminal/ui.py
Enables cycling through random hints in the footer.
- Using a hotkey to manually go to next hint
- Periodically cycle through footer hints automatically
This is in preparation to #1484, where we add contexts and the footer displays only the context-specific hotkey hints.
- If this is good, the next step could involve making the footer's cycle period a user setting.
- Deciding the hotkey to go to next hint: I've currently used `Tab`, but that's subject to change on discussion.
- Deciding the default cycle period: I've currently set it to 30 seconds, but we could increase it.
=> Add manual cycling of random hints in footer

docs/hotkeys.md, zulipterminal/config/keys.py
Groups key bindings from message actions into the new categories:
- Compose: New Message
- Compose: Replies
And in the 2nd commit, suggests renaming the "Composing a message" category to "Writing a message" category, to improve clarity, in contrast with the newly added categories.
=> Create new help categories related to opening compose box

docs/hotkeys.md, zulipterminal/config/keys.py
- Groups commands that switch narrows
- Improves their help descriptions
Feedback on the following are needed:
- name of the chosen help category
- order of the commands within the narrowing category
- help descriptions
=> Group narrowing commands and improve descriptions

tests/ui_tools/test_boxes.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py
Uses the existing confirmation popup to confirm whether user wants to exit the compose box upon pressing `Esc`, Enabling the user to go back and save their draft from compose.
=> Improve handling Esc during message compose

README.md, docs/FAQ.md, docs/hotkeys.md, tests/cli/test_run.py, tests/core/test_core.py, zulipterminal/cli/run.py, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/ui_tools/boxes.py
Create a new command OPEN_IN_TERMINAL_EDITOR (default `ctrl o`) for editing the current message in terminal editor with python tempfile.
I am using helix as my terminal editor and when I write in terminal I found myself using it's shortcut. 
[![Composing in terminal editor](https://asciinema.org/a/3CsC3bfnwZl2gZFHYoxSP22tM.png)](https://asciinema.org/a/3CsC3bfnwZl2gZFHYoxSP22tM)
=> Edit message in a terminal editor subprocess

docs/hotkeys.md, zulipterminal/config/keys.py
Adds the following new help categories to remove the corresponding context-suffixes (in parentheses) from help texts:
- Stream information ("from stream information" suffixes)
- Message information ("from message information" suffixes)
- User list actions ("from user list" suffixes)
That removes parantheses from all the help texts.
Each of the categories are added in their own commit, for readability.
A new command entry `NARROW_TO_USER_PM` is also added to the user list actions.
This PR is about removing the contexts mentioned in parentheses as suffixes. And it removes all of them.
But, it also introduces new parentheses for the help category names itself.
I went with this because
1. There is not much repetition of the content in the parentheses
2. Length constraints apply to help texts, …
=> Add new help categories to remove parentheses (context) from help texts

docs/hotkeys.md, tools/lint-hotkeys, zulipterminal/config/keys.py, zulipterminal/core.py, zulipterminal/model.py, zulipterminal/ui_tools/views.py
Allow copying traceback from the Exception has occurred popup.
| Before | After |
|--------|--------|
| ![image](https://github.com/zulip/zulip-terminal/assets/110327345/6160edc8-965c-45e4-a139-aa181138ca3c)| ![image](https://github.com/zulip/zulip-terminal/assets/110327345/49e57e35-43c3-418f-bec1-6c4693f887a6)|
| Traceback copy feature wasn't available before | ![image](https://github.com/zulip/zulip-terminal/assets/110327345/a7e85cc5-c7e9-4181-88a7-d582d84fe851)|
=> Copy traceback from the Exception popup

docs/developer-file-overview.md, tests/model/test_model.py, tests/widget/test_widget.py, zulipterminal/api_types.py, zulipterminal/model.py, zulipterminal/ui_tools/messages.py, zulipterminal/widget.py
Adds support for TODO Widget
| Before | After| Webapp |
|--------|--------|--------|
| ![image](https://github.com/user-attachments/assets/e42d0f26-262b-4f13-be2e-5a22a7a17844) | ![image](https://github.com/user-attachments/assets/b51f20de-f5f4-4d17-9847-f315519ac31a) | ![image](https://github.com/user-attachments/assets/ae9a6b97-a251-4236-b9b7-bf4f9d8d41c8) |
=> Add support for TODO Widget on ZT

tests/model/test_model.py, tests/ui_tools/test_messages.py, tests/ui_tools/test_popups.py, zulipterminal/api_types.py, zulipterminal/model.py, zulipterminal/ui_tools/messages.py, zulipterminal/ui_tools/views.py
- Prepares for the deprecation of user metadata from messages' reactions and reaction events
- Supports both `user_id` (ZFL>=2) and `user["id"]` for messages' reactions (with added test cases)
- Supports both `user_id` (ZFL>=2) and `user["user_id"]` for reaction events (with added test cases)
- Introduces a common `get_user_id_from_reaction()` for handling the different possible fields
- Switches to using `_all_users_by_id["user_id"]` to remove dependency on `reaction["user"]["full_name"]
- Improves the `ReactionEvent` schema to support both versions
- Fixes a bug in reaction event handling (remove op), and adds tests covering the missing cases
- Refactors the reactions' functions a bit before the above changes
=> Preparation for deprecating reactions' user metadata

zulipterminal/ui_tools/messages.py
Small PR - resolves the `bs4` deprecation warnings which you can see in the [CI logs](https://github.com/zulip/zulip-terminal/actions/runs/14682638921/job/41207209285#step:8:80):
```python
/home/runner/work/zulip-terminal/zulip-terminal/zulipterminal/ui_tools/messages.py:941: DeprecationWarning: Access to deprecated property nextSibling. (Replaced by next_sibling) -- Deprecated since version 4.0.0.
/home/runner/work/zulip-terminal/zulip-terminal/zulipterminal/ui_tools/messages.py:918: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
/home/runner/work/zulip-terminal/zulip-terminal/zulipterminal/ui_tools/messages.py:940: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since …
```
=> messages: migrate to new bs4 API
