- README.md
- display.py
- requirements.txt
- run.py
Add Requirements.txt.
Ease process for running Zulip-Terminal using `run.py`.
> Zulip-Terminal: Add annotations to functions and add README.md.

- ui.py
- ui_tools.py
> UI: Fix distracted borders due to UTF-8 encoding of messages.

- core.py
- run.py
- ui.py
Here is the preview for light theme:
#15 #6
> Added Light Theme

- zulipterminal/core.py
- zulipterminal/model.py
Update message requests were lost till messages haven't
been fetched for the first time. Fixed by keeping track of them.
> Model: Receive new message updates while loading old messages.

- zulipterminal/core.py
- zulipterminal/ui_tools.py
Use `[['is', 'private']]` in narrow to get all
private messages.
> UI: Make `Private messages` button functional..

- README.md
- requirements.txt
- run.py
- tests/conftest.py
- tests/helper/test_helper.py
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools.py
Add `pytest-pep8` to requirements.
Update README to include linting test.
> lint: Make code PEP8 compatible.

- README.md
- zulipterminal/ui_tools.py
Use `s` to narrow to a topic.
Use `S` to narrow to a stream.
> hotkeys: Swap `s` and `S` hotkeys.

- zulipterminal/core.py
- zulipterminal/model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools.py
Show stream colors same as the web version.
> UI: Show different colors for offline/online users.

- zulipterminal/model.py
- zulipterminal/ui.py
This PR fixes the failures we had while running the `pytest linter`
> Make code base compliant with PEP-8

- zulipterminal/core.py
> core: fix crashing when no messages in the stream.

- tests/conftest.py
- tests/helper/test_helper.py
> mypy : Annotate test_helper.py and conftest.py using mypy.

- README.md
- zulipterminal/ui_tools.py
> hotkeys: Add `R` to reply to the author of a message.

- tests/helper/test_helper.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui_tools/views.py
Fix failing test for update_flag.
Code cleanup.
> unread count: Increase unread counter for new messages.

- README.md
Add `j`, `k`, `J` and `K` hotkeys.
> README: Improve guidelines for installation.

- zulipterminal/core.py
> core: Set `ZulipTerminal/0.1.0` as User-Agent.

- .gitignore
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/buttons.py
- zulipterminal/ui_tools/utils.py
- zulipterminal/ui_tools/views.py
Add .mypy_cache to .gitignore.
> mypy: Fix mypy errors.

- tests/conftest.py
- tests/core/test_core.py
- tests/helper/test_helper.py
- zulipterminal/core.py
Allow setting foucs_position to 0 in stream narrow.
> test: Write tests for `controller.narrow_to_stream`.

- zulipterminal/core.py
- zulipterminal/model.py
- zulipterminal/ui_tools/boxes.py
> compose: Display emails of other recipients on PM reply.

- Pipfile
- requirements.txt
- tests/core/test_core.py
- zulipterminal/core.py
- zulipterminal/model.py
- zulipterminal/ui_tools/boxes.py
LineBox is dispositioned due to urwid assigning 1 space instead of
2 to symbols.
> emoji: Show emojis for a message in new line.

- README.md
- config.py
- zulipterminal/core.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/views.py
Switch between editor and normal mode to allow all
key presses while composing messages.
> hotkeys: Use KEY_BINDINGS in `config.py` for key presses.

- zulipterminal/helper.py
This fixes the error message "Controller has no attribute view".
> unread_count: Update unread count only after view if loaded.

- README.md
- tests/conftest.py
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/views.py
Set `/` to focus on `Search Box` and `esc` to focus on message
view.
> search: Add feature to search for messages.

- .codecov.yml
- .travis.yml
- README.md
> codecov: Setup .codecov.yml file.

- tests/core/test_core.py
- zulipterminal/core.py
I was just reading the code for the first time, and these changes looked useful, if relatively minor.
> Minor refactoring of core.py (Controller)

- zulipterminal/model.py
Again, was working on following this, and saw some potential opportunities for clarity - let me know if you agree!
The commits are split to make it a little simpler to follow.
Tests were useful, to modify the code and keep them passing :)
> model: get_all_users() refactoring

- tests/ui/test_ui.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/buttons.py
This remove distracted line boxes with old emojis.
> ui: Change emoji's for home and private messages.

- tests/conftest.py
- tests/core/test_core.py
- tests/model/test_model.py
- tests/ui/test_utils.py
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/utils.py
- zulipterminal/ui_tools/views.py
@punchagan I will rebase these commits with tests after you approve these changes. Thanks.
> Ignore muted topics and streams.

- README.md
- zulipterminal/cli/run.py
Add instructions and tips for debugging in README.
> debugging: Write sys.stdout data in /tmp/debug.log.

- tests/ui/test_ui.py
- tests/ui/test_ui_tools.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/views.py
This is first version of view.footer. I am thinking of including help text at the bottom of the view too.
> view: Display current narrow at the bottom of the view.

- tests/ui/test_ui.py
- tests/ui/test_ui_tools.py
- zulipterminal/config.py
- zulipterminal/core.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/buttons.py
- zulipterminal/ui_tools/views.py
@punchagan this looks like a better idea. I would love some review from you on this.
> hotkeys: Show help menu on pressing `?`.

- README.md
- tests/core/test_core.py
- tests/ui/test_ui.py
- zulipterminal/core.py
- zulipterminal/model.py
- zulipterminal/ui.py
Register for 'typing' event and display 'user is typing...' when
receing 'start' typing events in the footer.
> footer: Receiving and display typing events.

- tests/conftest.py
- zulipterminal/model.py
This fixes the bug for me, and adds some cross-realm bot data as currently in czo.
I tried to generalize the tests to cover the case in question, but there appear to be issues with pytest or the way the code/tests work, which I couldn't bypass - and it seems important to get this fix in :)
> Fix issue with internal (cross-realm) bots

- README.md
This adds some more shields and places the chat first.
> README: Reorder & add more 'shields' (pypi/python/mypy).

- README.md
We should probably have a tool for keeping these synchronized to the current repo `config.py`, but for now we've got extra commands not currently included, and this also puts them in some sort of order similar to how a recent commit did so for `config.py`.
> README: Manually sync key list to config.py.

- zulipterminal/ui_tools/boxes.py
Also do minor refactor of keypress code.
**NOTE** Since this is minor, I will merge this in the next 24-48h unless I hear anything different.
> Polish WriteBox: Use 'Topic' title & cleaner box joins for stream.

- tests/model/test_model.py
- tests/ui/test_ui.py
- tests/ui/test_ui_tools.py
- zulipterminal/model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/views.py
This is an improved replacement for #109.
> Pinned message UI/backend & refactor of stream setup in model

- README.md
These are some slight changes to the text, as well as some extra guidance on whether things are loading, and extra details on zuliprc files, including the updated options.
Note: This was prompted by issues that Sameer Choubey was having, and they agreed this was an improvement, at least from their perspective.
> README: Remove installation numbered steps; Improve zuliprc detail.

- tests/cli/test_run.py
- zulipterminal/cli/run.py
This makes handling colors on the console a little easier :)
> run: Refactor color code use into in_color function.

- tests/conftest.py
- tests/model/test_model.py
This started as one commit to improve the consistency between fixtures, and the followup to clarify a test, and then a follow-up commit which makes things clearer and simpler in terms of knowing the active user - and potentially testing with other user details later, even.
I would particularly like review of the first commit, as I'd like the intent of the tests to be confirmed in terms of the test ids (descriptions) that I added.
> Improve fixture consistency

- CHANGELOG.md
This should cover recent changes, along with #265, which it seems logical to include here given that PR has multiple commits.
> changelog: Summarize recent changes not included in commits/PRs.

- CHANGELOG.md
- zulipterminal/ui_tools/boxes.py
Fixes #239
Updates CHANGELOG.md
> Fix quoting original message, not rendered version

- README.md
- zulipterminal/config/keys.py
This combines #261 and #303, with commits by @vhawk19 and @mregdos respectively.
In combination, this closes #208.
I've cherry-picked these onto this branch/PR, and have amended the text of the commits to fit with the style we have been using recently, and for consistency between the two commits.
Thanks @vhawk19 & @mregdos ! :+1:
> Quit documentation improvements by vhawk19 and mregdos

- zulipterminal/config/keys.py
The purpose of this change is to ensure that help menu has guaranteed ordering.
Fixes #307.
> keys: convert KEY_BINDINGS from Dict to OrderedDict.

- tests/model/test_model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/buttons.py
- zulipterminal/ui_tools/views.py
I pooled together some refactors which I came across while reading code before a feature addition.
> Some miscellaneous fixes/refactors.

- zulipterminal/model.py
Now only one data-structure is necessary for mapping event names (to
associated callback methods), rather than relying upon a separate list
which could become unsynchronized with the mapping.
The switch to an OrderedDict simplifies testing.
Discussed at https://chat.zulip.org/#narrow/stream/49-development-help/topic/event.20names.2Ftypes/near/753673
> model: Use event callback mapping when registering desired events

- tests/ui/test_ui_tools.py
Address the failing bug with a test which is marked to fail(#402)
> test_ui_tools: Add failing test for nested blockquote.

- requirements.txt
- setup.py
- zulipterminal/ui_tools/boxes.py
This only requires a small change, to bring us up to date to using the latest mypy release.
Note that this does not currently require an update to the Pipfile, as to support PyPy we had to remove it and install it separately.
> Upgrade to mypy 0.740.

- tests/conftest.py
- tests/model/test_model.py
- tests/ui/test_ui.py
- zulipterminal/model.py
- zulipterminal/ui.py
This idea was mentioned recently, and seems pretty useful when you have multiple organizations (realms), so I'm putting this small PR out there to see how well it works cross-platform and inspire discussion in this direction.
> Add organization name to notifications & title bar

- Pipfile
- requirements.txt
- setup.py
Urwid 2.1.0 has neat features such as the true color support.
> requirements: Update Urwid from 2.0.1 to 2.1.0.

- zulipterminal/core.py
- zulipterminal/model.py
To re-summarize:
* Remove unused TypedDict
* Simplify loop into `in` conditional + indexing
* Migrate remaining `Event` parameters to `_handle_*` methods to use `event` name
* Use `message` in preference to `response` in `_handle_message_event`
> Tidy & add further consistency to model.py

- setup.cfg
- tests/config/test_themes.py
- tests/conftest.py
- tests/core/test_core.py
- tests/model/test_model.py
- tests/ui/test_ui_tools.py
- tests/ui_tools/test_boxes.py
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/buttons.py
- zulipterminal/ui_tools/views.py
Various source files modified, including tests.
Enforced through change to setup.cfg, which affects tools/lint-all and Travis CI.
> linting: Support pycodestyle E226 (arithmetic spacing)

- docs/FAQ.md
The change feels a bit scrupulous but should be useful to have in any case.
> FAQ: Amend hotkeys section to remove the obsolete context

- README.md
- setup.py
- zulipterminal/version.py
Given the project is marked as official after the following change, this
is a good opportunity to improve and synchronize the title between the
README.md and setup.py files (used on PyPI):
https://github.com/zulip/zulip/commit/0b3d14a408634ce26ba94acab7451bd185a786d9
To avoid duplication of the project title in the 'long description' text
on PyPI, we remove the first line read from README.md.
> Improve & sync project description

- tests/model/test_model.py
- zulipterminal/model.py
All other events use 'op' instead of 'operation'. As of feature level 32 this is also the case in the update_message_flags event.
Tests amended to use new fixture over feature levels None/31/32.
Fixes #786.
> model: Support standard field 'op' in update_message_flags events.

- README.md
This is a draft to document some of the git commit text styles we've been following recently, which aren't monitored by gitlint.
Feedback or additions welcome!
> Improve notes on project commit style & use of gitlint

- README.md
This is a follow-up on discussion in https://chat.zulip.org/#narrow/stream/9-issues/topic/Password.20reset.20is.20not.20working
> Clarify wording on resetting passwords.

- README.md
Fixes #788.
Thanks for the feedback @Laanan :+1:
> README: Add note for configuration with insecure/self-signed-cert setup.

- tests/model/test_model.py
- tests/ui_tools/test_boxes.py
- zulipterminal/model.py
- zulipterminal/ui.py
- zulipterminal/ui_tools/boxes.py
- zulipterminal/ui_tools/buttons.py
This takes a few aspects from @prah23 's #845 and puts some refactoring underneath to make some of the bundled changes a little clearer - feedback welcome
> WriteBox refactor with #845

- zulipterminal/core.py
> bugfix: core: Fix ZT crash due to AttributeErrors.

- tests/model/test_model.py
> Tidy up reaction tests (prep for reaction event improvements)

- .github/workflows/lint-and-test.yml
https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
https://app.codecov.io/gh/zulip/zulip-terminal/compare/1137
> github/codecov: Update codecov-action to v2

- docs/developer-file-overview.md
- tools/lint-all
- tools/lint-docstring
- This PR adds docstrings to the source files in the codebase
- Add a CI Action which ensures the document matches the expectations from the docstrings
- Generate the document from docstrings
Fixes #892 
**Tested?** 
- first commit: Adds docstrings to the source files
- second commit: Adds linting for developer-file-overview.md
> [WIP]  Add docstrings to each source file and add linting for developer-file-overview.

- README.md
Fixes #1256 by improving documentation, as verified by reporter.
> README: Expand documentation on fetching zuliprc files.

- pyproject.toml
- setup.py
- tests/config/test_themes.py
- tests/core/test_core.py
- tests/model/test_model.py
- tools/font-styles-test
- zulipterminal/cli/run.py
- zulipterminal/config/themes.py
Ruff is moving fast and adding lots of new features - which is great - but one consequence is that automatically installing the newest version with the new features can trigger CI failures due to extra linting. This PR fixes an outstanding result of that, before pinning ruff at it's current version.
It also then extends the ruff coverage to check more rules after slightly adjusting code in prior commits: G, PIE, RSE.
**Tested?** 
This is blocking CI right now due to the unpinned ruff, so will likely be merged soon.
> Pin ruff and add checks for smaller additional rules

- README.md
- Clarify the commit message style section
- Add a new explicit section on structuring commits, discussing 'developmental-style' vs 'minimal coherent style' commits, and why the latter is useful
More notes in the commits.
**Tested?** 
Feedback welcome, particularly from new contributors!
> Documentation: Improve commit message style & Add section on Structuring Commits

- README.md
This documents the availability of `tools/lint-docstring` and `tools/generate-hotkeys.py`.
**Tested?**
> README: Add note regarding use of tools to synchronize source with docs.

- tests/ui_tools/test_popups.py
- zulipterminal/ui_tools/views.py
This fixes #1339 
**Tested?** 
> refactor: seperate displaybox and simplyfing text for hotkeys(Fixed #1339)

- README.md
- docs/FAQ.md
Overall, this shrinks the top of the README to focus on the core features in the About section, leaving queries on platform and python version support to the FAQ - while using/adding badges to provide quick links to this information. Installation/Running/Configuration sections then follow.
The main additional content here is a more detailed section on engaging within #zulip-terminal, intended to more clearly welcome users and developers, while also emphasizing some Community norms that are more relevant to the stream.
The remaining commits are to reorganize existing content in the README
- restructuring the Feature status section
- extracting parts into their own elements in the FAQ, one commit at a time, via 'badges'
There is one commit included at the end, which substitutes my branch …
> README/FAQ Restructuring

- README.md
This aims to improve the phrasing of the linting and gitlint sections, including improving the structure and motivation for using different tools.
> README: Improve linting text

- tests/conftest.py
- tests/model/test_model.py
- tests/ui/test_ui_tools.py
- tests/ui_tools/test_messages.py
- zulipterminal/core.py
- zulipterminal/helper.py
- zulipterminal/model.py
- zulipterminal/ui_tools/messages.py
- zulipterminal/ui_tools/views.py
This is pure refactoring work that became commits to improve the code, while exploring how best to fix the message focus issue (message id vs list id).
> Refactoring before further work on message-focus solution

- pyproject.toml
- setup.py
- tests/cli/test_run.py
- tests/model/test_model.py
- zulipterminal/ui_tools/messages.py
Upgrade infrastructure tooling. This found a few bugs, and exposed a test that had little use.
This suggested other changes which may follow in another branch/PR.
This was prompted by testing later mypy versions to determine an unexpected lack of report from mypy in another PR.
> Upgrade ruff (0.0.267), mypy (1.3.0), typos (1.14.9)

- zulipterminal/api_types.py
- zulipterminal/model.py
This was inspired by starting to review another PR and recalling the complexity in this event.
This PR documents missing fields, though most are unused so are commented-out at this point.
More importantly, this aims to accurately split the fields into three groups:
- those always present (BaseUpdateMessageEvent)
- those present if the event updates the content of a message (UpdateMessageContentEvent)
- those present if the event updates the location of messages (UpdateMessagesLocationEvent)
This makes it much clearer when fields are present, and how to determine whether a given update_message event is one or both of the derived types, based on the presence of particular fields.
As a result _handle_update_message_event becomes slightly more complex and requires casting to those explicit …
> Split & further document update_message event type

- tests/conftest.py
- tests/core/test_core.py
- tests/model/test_model.py
- tests/ui_tools/test_boxes.py
- zulipterminal/config/ui_mappings.py
- zulipterminal/helper.py
- zulipterminal/model.py
This defines user data more centrally and clearly in the model.
Next step is to encapsulate this data properly and improve the naming.
> Model: Improve users data handling & typing

- docs/FAQ.md
Add Alaccrity to the successfully run terminal emulators list. Ive encountered no issue after using it for a month with Alaccrity
> docs: Add Alacritty to successfully run terminal list

- .github/workflows/lint-and-test.yml
- README.md
- setup.py
This:
- applies gitlint to the PR branch, in the first phase of CI
- adds the gitlint install-hook step to documented development environment setup to support this
This changes gitlint to become a requirement to pass onto the isolated commits phase.
Note that it's unclear if gitlint is sufficiently reliable to include in CI as a requirement generally (see eg. https://chat.zulip.org/#narrow/stream/43-automated-testing/topic/Gitlint.20false.20positive.3F).
However, this PR is intended to automate feedback given limited maintainer/reviewer time.
In future:
- this could be reduced to a diagnostic step only (does not block PR passing CI)
- this could be reordered, so that in runs in tandem with the isolated commits or similar
This was tested with additional commits that fail gitlint, which …
> lint-and-test: Require valid commit style for branch commits.

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint-and-test.yml
This updates to use the new major versions of `checkout`, `setup-python` and `codeql-action`.
While permissions are controlled elsewhere, this also explicitly controls permissions on a per-workflow/job basis.
> CI: Upgrade GitHub actions & limit permissions

- .github/ISSUE_TEMPLATE/01_crash.md
- .github/ISSUE_TEMPLATE/02_bug.md
- .github/ISSUE_TEMPLATE/03_parity.md
- .github/ISSUE_TEMPLATE/04_platform.md
This aims to fix the issue templates, 2 of which did not appear to show properly in the issue chooser - and in the merged source showed with yaml errors.
This uses a consistent format of `'label part1,'`, ie. includes a trailing comma, to indicate that additional labels should be in the quote after the comma.
> bugfix: github: Adjust label yaml quoting syntax.

- .mailmap
Update mailmap file for new contributors, in preparation for Zulip 9.0 release.
> mailmap: Add entries for Niloth P & Sashank Ravipati.

- docs/FAQ.md
- setup.py
To establish a baseline to push a last release with python 3.7, this provides matching dependencies for such a case.
> Synchronize dependencies compatible with Python 3.7
